import type { FC } from "react";
import {
    Infinity,
    Activity,
    ActivityHeart,
    Airplay,
    Airpods,
    AlarmClock,
    AlarmClockCheck,
    AlarmClockMinus,
    AlarmClockOff,
    AlarmClockPlus,
    AlertCircle,
    AlertHexagon,
    AlertOctagon,
    AlertSquare,
    AlertTriangle,
    AlignBottom01,
    AlignBottom02,
    AlignCenter,
    AlignHorizontalCentre01,
    AlignHorizontalCentre02,
    AlignJustify,
    AlignLeft,
    AlignLeft01,
    AlignLeft02,
    AlignRight,
    AlignRight01,
    AlignRight02,
    AlignTopArrow01,
    AlignTopArrow02,
    AlignVerticalCenter01,
    AlignVerticalCenter02,
    Anchor,
    Annotation,
    AnnotationAlert,
    AnnotationCheck,
    AnnotationDots,
    AnnotationHeart,
    AnnotationInfo,
    AnnotationPlus,
    AnnotationQuestion,
    AnnotationX,
    Announcement01,
    Announcement02,
    Announcement03,
    Archive,
    ArrowBlockDown,
    ArrowBlockLeft,
    ArrowBlockRight,
    ArrowBlockUp,
    ArrowCircleBrokenDown,
    ArrowCircleBrokenDownLeft,
    ArrowCircleBrokenDownRight,
    ArrowCircleBrokenLeft,
    ArrowCircleBrokenRight,
    ArrowCircleBrokenUp,
    ArrowCircleBrokenUpLeft,
    ArrowCircleBrokenUpRight,
    ArrowCircleDown,
    ArrowCircleDownLeft,
    ArrowCircleDownRight,
    ArrowCircleLeft,
    ArrowCircleRight,
    ArrowCircleUp,
    ArrowCircleUpLeft,
    ArrowCircleUpRight,
    ArrowDown,
    ArrowDownLeft,
    ArrowDownRight,
    ArrowLeft,
    ArrowNarrowDown,
    ArrowNarrowDownLeft,
    ArrowNarrowDownRight,
    ArrowNarrowLeft,
    ArrowNarrowRight,
    ArrowNarrowUp,
    ArrowNarrowUpLeft,
    ArrowNarrowUpRight,
    ArrowNext,
    ArrowPrevious,
    ArrowRight,
    ArrowSquareDown,
    ArrowSquareDownLeft,
    ArrowSquareDownRight,
    ArrowSquareLeft,
    ArrowSquareRight,
    ArrowSquareUp,
    ArrowSquareUpLeft,
    ArrowSquareUpRight,
    ArrowUp,
    ArrowUpLeft,
    ArrowUpRight,
    ArrowsDown,
    ArrowsLeft,
    ArrowsRight,
    ArrowsTriangle,
    ArrowsUp,
    Asterisk01,
    Asterisk02,
    AtSign,
    Atom01,
    Atom02,
    Attachment01,
    Attachment02,
    Award01,
    Award02,
    Award03,
    Award04,
    Award05,
    Backpack,
    Bank,
    BankNote01,
    BankNote02,
    BankNote03,
    BarChart01,
    BarChart02,
    BarChart03,
    BarChart04,
    BarChart05,
    BarChart06,
    BarChart07,
    BarChart08,
    BarChart09,
    BarChart10,
    BarChart11,
    BarChart12,
    BarChartCircle01,
    BarChartCircle02,
    BarChartCircle03,
    BarChartSquare01,
    BarChartSquare02,
    BarChartSquare03,
    BarChartSquareDown,
    BarChartSquareMinus,
    BarChartSquarePlus,
    BarChartSquareUp,
    BarLineChart,
    BatteryCharging01,
    BatteryCharging02,
    BatteryEmpty,
    BatteryFull,
    BatteryLow,
    BatteryMid,
    Beaker01,
    Beaker02,
    Bell01,
    Bell02,
    Bell03,
    Bell04,
    BellMinus,
    BellOff01,
    BellOff02,
    BellOff03,
    BellPlus,
    BellRinging01,
    BellRinging02,
    BellRinging03,
    BellRinging04,
    BezierCurve01,
    BezierCurve02,
    BezierCurve03,
    BluetoothConnect,
    BluetoothOff,
    BluetoothOn,
    BluetoothSignal,
    Bold01,
    Bold02,
    BoldSquare,
    BookClosed,
    BookOpen01,
    BookOpen02,
    Bookmark,
    BookmarkAdd,
    BookmarkCheck,
    BookmarkMinus,
    BookmarkX,
    Box,
    Brackets,
    BracketsCheck,
    BracketsEllipses,
    BracketsMinus,
    BracketsPlus,
    BracketsSlash,
    BracketsX,
    Briefcase01,
    Briefcase02,
    Browser,
    Brush01,
    Brush02,
    Brush03,
    Building01,
    Building02,
    Building03,
    Building04,
    Building05,
    Building06,
    Building07,
    Building08,
    Bus,
    Calculator,
    Calendar,
    CalendarCheck01,
    CalendarCheck02,
    CalendarDate,
    CalendarHeart01,
    CalendarHeart02,
    CalendarMinus01,
    CalendarMinus02,
    CalendarPlus01,
    CalendarPlus02,
    Camera01,
    Camera02,
    Camera03,
    CameraLens,
    CameraOff,
    CameraPlus,
    Car01,
    Car02,
    Certificate01,
    Certificate02,
    ChartBreakoutCircle,
    ChartBreakoutSquare,
    Check,
    CheckCircle,
    CheckCircleBroken,
    CheckDone01,
    CheckDone02,
    CheckHeart,
    CheckSquare,
    CheckSquareBroken,
    CheckVerified01,
    CheckVerified02,
    CheckVerified03,
    ChevronDown,
    ChevronDownDouble,
    ChevronLeft,
    ChevronLeftDouble,
    ChevronNext,
    ChevronNextDouble,
    ChevronPrevious,
    ChevronPreviousDouble,
    ChevronRight,
    ChevronRightDouble,
    ChevronSelectorHorizontal,
    ChevronSelectorVertical,
    ChevronUp,
    ChevronUpDouble,
    ChromeCast,
    Circle,
    CircleCut,
    Clapperboard,
    Clipboard,
    ClipboardAttachment,
    ClipboardCheck,
    ClipboardDownload,
    ClipboardMinus,
    ClipboardPlus,
    ClipboardX,
    Clock,
    ClockCheck,
    ClockFastForward,
    ClockPlus,
    ClockRefresh,
    ClockRewind,
    ClockSnooze,
    ClockStopwatch,
    Cloud01,
    Cloud02,
    Cloud03,
    CloudBlank01,
    CloudBlank02,
    CloudLightning,
    CloudMoon,
    CloudOff,
    CloudRaining01,
    CloudRaining02,
    CloudRaining03,
    CloudRaining04,
    CloudRaining05,
    CloudRaining06,
    CloudSnowing01,
    CloudSnowing02,
    CloudSun01,
    CloudSun02,
    CloudSun03,
    Code01,
    Code02,
    CodeBrowser,
    CodeCircle01,
    CodeCircle02,
    CodeCircle03,
    CodeSnippet01,
    CodeSnippet02,
    CodeSquare01,
    CodeSquare02,
    Codepen,
    Coins01,
    Coins02,
    Coins03,
    Coins04,
    CoinsHand,
    CoinsStacked01,
    CoinsStacked02,
    CoinsStacked03,
    CoinsStacked04,
    CoinsSwap01,
    CoinsSwap02,
    Colors,
    Colors1,
    Columns01,
    Columns02,
    Columns03,
    Command,
    Compass,
    Compass01,
    Compass02,
    Compass03,
    Container,
    Contrast01,
    Contrast02,
    Contrast03,
    Copy01,
    Copy02,
    Copy03,
    Copy04,
    Copy05,
    Copy06,
    Copy07,
    CornerDownLeft,
    CornerDownRight,
    CornerLeftDown,
    CornerLeftUp,
    CornerRightDown,
    CornerRightUp,
    CornerUpLeft,
    CornerUpRight,
    CpuChip01,
    CpuChip02,
    CreditCard01,
    CreditCard02,
    CreditCardCheck,
    CreditCardDown,
    CreditCardDownload,
    CreditCardEdit,
    CreditCardLock,
    CreditCardMinus,
    CreditCardPlus,
    CreditCardRefresh,
    CreditCardSearch,
    CreditCardShield,
    CreditCardUp,
    CreditCardUpload,
    CreditCardX,
    Crop01,
    Crop02,
    Cryptocurrency01,
    Cryptocurrency02,
    Cryptocurrency03,
    Cryptocurrency04,
    Cube01,
    Cube02,
    Cube03,
    Cube04,
    CubeOutline,
    CurrencyBitcoin,
    CurrencyBitcoinCircle,
    CurrencyDollar,
    CurrencyDollarCircle,
    CurrencyEthereum,
    CurrencyEthereumCircle,
    CurrencyEuro,
    CurrencyEuroCircle,
    CurrencyPound,
    CurrencyPoundCircle,
    CurrencyRuble,
    CurrencyRubleCircle,
    CurrencyRupee,
    CurrencyRupeeCircle,
    CurrencyYen,
    CurrencyYenCircle,
    Cursor01,
    Cursor02,
    Cursor03,
    Cursor04,
    CursorBox,
    CursorClick01,
    CursorClick02,
    Data,
    Database01,
    Database02,
    Database03,
    Dataflow01,
    Dataflow02,
    Dataflow03,
    Dataflow04,
    Delete,
    Diamond01,
    Diamond02,
    Dice1,
    Dice2,
    Dice3,
    Dice4,
    Dice5,
    Dice6,
    Disc01,
    Disc02,
    DistributeSpacingHorizontal,
    DistributeSpacingVertical,
    Divide01,
    Divide02,
    Divide03,
    Divider,
    Dotpoints01,
    Dotpoints02,
    DotsGrid,
    DotsHorizontal,
    DotsVertical,
    Download01,
    Download02,
    Download03,
    Download04,
    DownloadCloud01,
    DownloadCloud02,
    Drop,
    Droplets01,
    Droplets02,
    Droplets03,
    Dropper,
    Edit01,
    Edit02,
    Edit03,
    Edit04,
    Edit05,
    Equal,
    EqualNot,
    Eraser,
    Expand01,
    Expand02,
    Expand03,
    Expand04,
    Expand05,
    Expand06,
    Eye,
    EyeOff,
    FaceContent,
    FaceFrown,
    FaceHappy,
    FaceId,
    FaceIdSquare,
    FaceNeutral,
    FaceSad,
    FaceSmile,
    FaceWink,
    FastBackward,
    FastForward,
    Feather,
    Figma,
    File01,
    File02,
    File03,
    File04,
    File05,
    File06,
    File07,
    FileAttachment01,
    FileAttachment02,
    FileAttachment03,
    FileAttachment04,
    FileAttachment05,
    FileCheck01,
    FileCheck02,
    FileCheck03,
    FileCode01,
    FileCode02,
    FileDownload01,
    FileDownload02,
    FileDownload03,
    FileHeart01,
    FileHeart02,
    FileHeart03,
    FileLock01,
    FileLock02,
    FileLock03,
    FileMinus01,
    FileMinus02,
    FileMinus03,
    FilePlus01,
    FilePlus02,
    FilePlus03,
    FileQuestion01,
    FileQuestion02,
    FileQuestion03,
    FileSearch01,
    FileSearch02,
    FileSearch03,
    FileShield01,
    FileShield02,
    FileShield03,
    FileX01,
    FileX02,
    FileX03,
    Film01,
    Film02,
    Film03,
    FilterFunnel01,
    FilterFunnel02,
    FilterLines,
    Fingerprint01,
    Fingerprint02,
    Fingerprint03,
    Fingerprint04,
    Flag01,
    Flag02,
    Flag03,
    Flag04,
    Flag05,
    Flag06,
    Flash,
    FlashOff,
    FlexAlignBottom,
    FlexAlignLeft,
    FlexAlignRight,
    FlexAlignTop,
    FlipBackward,
    FlipForward,
    Folder,
    FolderCheck,
    FolderClosed,
    FolderCode,
    FolderDownload,
    FolderLock,
    FolderMinus,
    FolderPlus,
    FolderQuestion,
    FolderSearch,
    FolderShield,
    FolderX,
    Framer,
    GamingPad01,
    GamingPad02,
    Gift01,
    Gift02,
    GitBranch01,
    GitBranch02,
    GitCommit,
    GitMerge,
    GitPullRequest,
    Glasses01,
    Glasses02,
    Globe01,
    Globe02,
    Globe03,
    Globe04,
    Globe05,
    Globe06,
    GlobeSlated01,
    GlobeSlated02,
    GoogleChrome,
    GraduationHat01,
    GraduationHat02,
    Grid01,
    Grid02,
    Grid03,
    GridDotsBlank,
    GridDotsBottom,
    GridDotsHorizontalCenter,
    GridDotsLeft,
    GridDotsOuter,
    GridDotsRight,
    GridDotsTop,
    GridDotsVerticalCenter,
    Hand,
    HardDrive,
    Hash01,
    Hash02,
    Heading01,
    Heading02,
    HeadingSquare,
    Headphones01,
    Headphones02,
    Heart,
    HeartCircle,
    HeartHand,
    HeartHexagon,
    HeartOctagon,
    HeartRounded,
    HeartSquare,
    Hearts,
    HelpCircle,
    HelpOctagon,
    HelpOctagon1,
    HelpSquare,
    Hexagon01,
    Hexagon02,
    Home01,
    Home02,
    Home03,
    Home04,
    Home05,
    HomeLine,
    HomeSmile,
    HorizontalBarChart01,
    HorizontalBarChart02,
    HorizontalBarChart03,
    Hourglass01,
    Hourglass02,
    Hourglass03,
    Hurricane01,
    Hurricane02,
    Hurricane03,
    Image01,
    Image02,
    Image03,
    Image04,
    Image05,
    ImageCheck,
    ImageDown,
    ImageIndentLeft,
    ImageIndentRight,
    ImageLeft,
    ImagePlus,
    ImageRight,
    ImageUp,
    ImageUser,
    ImageUserCheck,
    ImageUserDown,
    ImageUserLeft,
    ImageUserPlus,
    ImageUserRight,
    ImageUserUp,
    ImageUserX,
    ImageX,
    Inbox01,
    Inbox02,
    InfoCircle,
    InfoHexagon,
    InfoOctagon,
    InfoSquare,
    IntersectCircle,
    IntersectSquare,
    Italic01,
    Italic02,
    ItalicSquare,
    Key01,
    Key02,
    Keyboard01,
    Keyboard02,
    Laptop01,
    Laptop02,
    LayerSingle,
    LayersThree01,
    LayersThree02,
    LayersTwo01,
    LayersTwo02,
    LayoutAlt01,
    LayoutAlt02,
    LayoutAlt03,
    LayoutAlt04,
    LayoutBottom,
    LayoutGrid01,
    LayoutGrid02,
    LayoutLeft,
    LayoutRight,
    LayoutTop,
    LeftIndent01,
    LeftIndent02,
    LetterSpacing01,
    LetterSpacing02,
    LifeBuoy01,
    LifeBuoy02,
    Lightbulb01,
    Lightbulb02,
    Lightbulb03,
    Lightbulb04,
    Lightbulb05,
    Lightning01,
    Lightning02,
    LineChartDown01,
    LineChartDown02,
    LineChartDown03,
    LineChartDown04,
    LineChartDown05,
    LineChartUp01,
    LineChartUp02,
    LineChartUp03,
    LineChartUp04,
    LineChartUp05,
    LineHeight,
    Link01,
    Link02,
    Link03,
    Link04,
    Link05,
    LinkBroken01,
    LinkBroken02,
    LinkExternal01,
    LinkExternal02,
    List,
    Loading01,
    Loading02,
    Loading03,
    Lock01,
    Lock02,
    Lock03,
    Lock04,
    LockKeyholeCircle,
    LockKeyholeSquare,
    LockUnlocked01,
    LockUnlocked02,
    LockUnlocked03,
    LockUnlocked04,
    LogIn01,
    LogIn02,
    LogIn03,
    LogIn04,
    LogOut01,
    LogOut02,
    LogOut03,
    LogOut04,
    Luggage01,
    Luggage02,
    Luggage03,
    MagicWand01,
    MagicWand02,
    Mail01,
    Mail02,
    Mail03,
    Mail04,
    Mail05,
    Map01,
    Map02,
    Mark,
    MarkerPin01,
    MarkerPin02,
    MarkerPin03,
    MarkerPin04,
    MarkerPin05,
    MarkerPin06,
    Maximize01,
    Maximize02,
    MedicalCircle,
    MedicalCross,
    MedicalSquare,
    Menu01,
    Menu02,
    Menu03,
    Menu04,
    Menu05,
    MessageAlertCircle,
    MessageAlertSquare,
    MessageChatCircle,
    MessageChatSquare,
    MessageCheckCircle,
    MessageCheckSquare,
    MessageCircle01,
    MessageCircle02,
    MessageDotsCircle,
    MessageDotsSquare,
    MessageHeartCircle,
    MessageHeartSquare,
    MessageNotificationCircle,
    MessageNotificationSquare,
    MessagePlusCircle,
    MessagePlusSquare,
    MessageQuestionCircle,
    MessageQuestionSquare,
    MessageSmileCircle,
    MessageSmileSquare,
    MessageSquare01,
    MessageSquare02,
    MessageTextCircle01,
    MessageTextCircle02,
    MessageTextSquare01,
    MessageTextSquare02,
    MessageXCircle,
    MessageXSquare,
    Microphone01,
    Microphone02,
    MicrophoneOff01,
    MicrophoneOff02,
    Microscope,
    Minimize01,
    Minimize02,
    Minus,
    MinusCircle,
    MinusSquare,
    Modem01,
    Modem02,
    Monitor01,
    Monitor02,
    Monitor03,
    Monitor04,
    Monitor05,
    Moon01,
    Moon02,
    MoonEclipse,
    MoonStar,
    Mouse,
    Move,
    MusicNote01,
    MusicNote02,
    MusicNotePlus,
    NavigationPointer01,
    NavigationPointer02,
    NavigationPointerOff01,
    NavigationPointerOff02,
    NotificationBox,
    NotificationMessage,
    NotificationText,
    Octagon,
    Package,
    PackageCheck,
    PackageMinus,
    PackagePlus,
    PackageSearch,
    PackageX,
    Paint,
    PaintPour,
    Palette,
    Paperclip,
    ParagraphSpacing,
    ParagraphWrap,
    Passcode,
    PasscodeLock,
    Passport,
    PauseCircle,
    PauseSquare,
    PenTool01,
    PenTool02,
    PenToolMinus,
    PenToolPlus,
    Pencil01,
    Pencil02,
    PencilLine,
    Pentagon,
    Percent01,
    Percent02,
    Percent03,
    Perspective01,
    Perspective02,
    Phone,
    Phone01,
    Phone02,
    PhoneCall01,
    PhoneCall02,
    PhoneHangUp,
    PhoneIncoming01,
    PhoneIncoming02,
    PhoneOutgoing01,
    PhoneOutgoing02,
    PhonePause,
    PhonePlus,
    PhoneX,
    PieChart01,
    PieChart02,
    PieChart03,
    PieChart04,
    PiggyBank01,
    PiggyBank02,
    Pilcrow01,
    Pilcrow02,
    PilcrowSquare,
    Pin01,
    Pin02,
    Placeholder,
    Plane,
    Play,
    PlayCircle,
    PlaySquare,
    Plus,
    PlusCircle,
    PlusSquare,
    Podcast,
    Power01,
    Power02,
    Power03,
    PresentationChart01,
    PresentationChart02,
    PresentationChart03,
    Printer,
    PuzzlePiece01,
    PuzzlePiece02,
    QrCode01,
    QrCode02,
    Receipt,
    ReceiptCheck,
    Recording01,
    Recording02,
    Recording03,
    Reflect01,
    Reflect02,
    RefreshCcw01,
    RefreshCcw02,
    RefreshCcw03,
    RefreshCcw04,
    RefreshCcw05,
    RefreshCw01,
    RefreshCw02,
    RefreshCw03,
    RefreshCw04,
    RefreshCw05,
    Repeat01,
    Repeat02,
    Repeat03,
    Repeat04,
    ReverseLeft,
    ReverseRight,
    RightIndent01,
    RightIndent02,
    Rocket01,
    Rocket02,
    RollerBrush,
    Route,
    Rows01,
    Rows02,
    Rows03,
    Rss01,
    Rss02,
    Ruler,
    Safe,
    Sale01,
    Sale02,
    Sale03,
    Sale04,
    Save01,
    Save02,
    Save03,
    Scale01,
    Scale02,
    Scale03,
    Scales01,
    Scales02,
    Scan,
    Scissors01,
    Scissors02,
    ScissorsCut01,
    ScissorsCut02,
    SearchLg,
    SearchMd,
    SearchRefraction,
    SearchSm,
    Send01,
    Send02,
    Send03,
    Server01,
    Server02,
    Server03,
    Server04,
    Server05,
    Server06,
    Settings01,
    Settings02,
    Settings03,
    Settings04,
    Share01,
    Share02,
    Share03,
    Share04,
    Share05,
    Share06,
    Share07,
    Shield01,
    Shield02,
    Shield03,
    ShieldDollar,
    ShieldOff,
    ShieldPlus,
    ShieldTick,
    ShieldZap,
    ShoppingBag01,
    ShoppingBag02,
    ShoppingBag03,
    ShoppingCart01,
    ShoppingCart02,
    ShoppingCart03,
    Shuffle01,
    Shuffle02,
    Signal01,
    Signal02,
    Signal03,
    Simcard,
    Skew,
    SkipBack,
    SkipForward,
    SlashCircle01,
    SlashCircle02,
    SlashDivider,
    SlashOctagon,
    Sliders01,
    Sliders02,
    Sliders03,
    Sliders04,
    Snowflake01,
    Snowflake02,
    SpacingHeight01,
    SpacingHeight02,
    SpacingWidth01,
    SpacingWidth02,
    Speaker01,
    Speaker02,
    Speaker03,
    Speedometer01,
    Speedometer02,
    Speedometer03,
    Speedometer04,
    Square,
    Stand,
    Star01,
    Star02,
    Star03,
    Star04,
    Star05,
    Star06,
    Star07,
    Stars01,
    Stars02,
    Stars03,
    StickerCircle,
    StickerSquare,
    Stop,
    StopCircle,
    StopSquare,
    Strikethrough01,
    Strikethrough02,
    StrikethroughSquare,
    Subscript,
    Sun,
    SunSetting01,
    SunSetting02,
    SunSetting03,
    Sunrise,
    Sunset,
    SwitchHorizontal01,
    SwitchHorizontal02,
    SwitchVertical01,
    SwitchVertical02,
    Table,
    Tablet01,
    Tablet02,
    Tag01,
    Tag02,
    Tag03,
    Target01,
    Target02,
    Target03,
    Target04,
    Target05,
    Telescope,
    Terminal,
    TerminalBrowser,
    TerminalCircle,
    TerminalSquare,
    TextInput,
    Thermometer01,
    Thermometer02,
    Thermometer03,
    ThermometerCold,
    ThermometerWarm,
    ThumbsDown,
    ThumbsUp,
    Ticket01,
    Ticket02,
    Toggle01Left,
    Toggle01Right,
    Toggle02Left,
    Toggle02Right,
    Toggle03Left,
    Toggle03Right,
    Tool01,
    Tool02,
    Train,
    Tram,
    Transform,
    Translate01,
    Translate02,
    Trash01,
    Trash02,
    Trash03,
    Trash04,
    TrendDown01,
    TrendDown02,
    TrendUp01,
    TrendUp02,
    Triangle,
    Trophy01,
    Trophy02,
    Truck01,
    Truck02,
    Tv01,
    Tv02,
    Tv03,
    Type01,
    Type02,
    TypeSquare,
    TypeStrikethrough01,
    TypeStrikethrough02,
    Umbrella01,
    Umbrella02,
    Umbrella03,
    Underline01,
    Underline02,
    UnderlineSquare,
    Upload01,
    Upload02,
    Upload03,
    Upload04,
    UploadCloud01,
    UploadCloud02,
    UsbFlashDrive,
    User01,
    User02,
    User03,
    UserCheck01,
    UserCheck02,
    UserCircle,
    UserDown01,
    UserDown02,
    UserEdit,
    UserLeft01,
    UserLeft02,
    UserMinus01,
    UserMinus02,
    UserPlus01,
    UserPlus02,
    UserRight01,
    UserRight02,
    UserSquare,
    UserUp01,
    UserUp02,
    UserX01,
    UserX02,
    Users01,
    Users02,
    Users03,
    UsersCheck,
    UsersDown,
    UsersEdit,
    UsersLeft,
    UsersMinus,
    UsersPlus,
    UsersRight,
    UsersUp,
    UsersX,
    Variable,
    VideoRecorder,
    VideoRecorderOff,
    Virus,
    Voicemail,
    VolumeMax,
    VolumeMin,
    VolumeMinus,
    VolumePlus,
    VolumeX,
    Wallet01,
    Wallet02,
    Wallet03,
    Wallet04,
    Wallet05,
    WatchCircle,
    WatchSquare,
    Waves,
    Webcam01,
    Webcam02,
    Wifi,
    WifiOff,
    Wind01,
    Wind02,
    Wind03,
    X,
    XCircle,
    XClose,
    XSquare,
    Youtube,
    Zap,
    ZapCircle,
    ZapFast,
    ZapOff,
    ZapSquare,
    ZoomIn,
    ZoomOut,
} from "@/components/foundations/icons";

const icons = [
    { name: "Activity", icon: Activity },
    { name: "Activity Heart", icon: ActivityHeart },
    { name: "Airplay", icon: Airplay },
    { name: "Airpods", icon: Airpods },
    { name: "Alarm Clock", icon: AlarmClock },
    { name: "Alarm Clock Check", icon: AlarmClockCheck },
    { name: "Alarm Clock Minus", icon: AlarmClockMinus },
    { name: "Alarm Clock Off", icon: AlarmClockOff },
    { name: "Alarm Clock Plus", icon: AlarmClockPlus },
    { name: "Alert Circle", icon: AlertCircle },
    { name: "Alert Hexagon", icon: AlertHexagon },
    { name: "Alert Octagon", icon: AlertOctagon },
    { name: "Alert Square", icon: AlertSquare },
    { name: "Alert Triangle", icon: AlertTriangle },
    { name: "Align Bottom 01", icon: AlignBottom01 },
    { name: "Align Bottom 02", icon: AlignBottom02 },
    { name: "Align Center", icon: AlignCenter },
    { name: "Align Horizontal Centre 01", icon: AlignHorizontalCentre01 },
    { name: "Align Horizontal Centre 02", icon: AlignHorizontalCentre02 },
    { name: "Align Justify", icon: AlignJustify },
    { name: "Align Left", icon: AlignLeft },
    { name: "Align Left 01", icon: AlignLeft01 },
    { name: "Align Left 02", icon: AlignLeft02 },
    { name: "Align Right", icon: AlignRight },
    { name: "Align Right 01", icon: AlignRight01 },
    { name: "Align Right 02", icon: AlignRight02 },
    { name: "Align Top Arrow 01", icon: AlignTopArrow01 },
    { name: "Align Top Arrow 02", icon: AlignTopArrow02 },
    { name: "Align Vertical Center 01", icon: AlignVerticalCenter01 },
    { name: "Align Vertical Center 02", icon: AlignVerticalCenter02 },
    { name: "Anchor", icon: Anchor },
    { name: "Annotation", icon: Annotation },
    { name: "Annotation Alert", icon: AnnotationAlert },
    { name: "Annotation Check", icon: AnnotationCheck },
    { name: "Annotation Dots", icon: AnnotationDots },
    { name: "Annotation Heart", icon: AnnotationHeart },
    { name: "Annotation Info", icon: AnnotationInfo },
    { name: "Annotation Plus", icon: AnnotationPlus },
    { name: "Annotation Question", icon: AnnotationQuestion },
    { name: "Annotation X", icon: AnnotationX },
    { name: "Announcement 01", icon: Announcement01 },
    { name: "Announcement 02", icon: Announcement02 },
    { name: "Announcement 03", icon: Announcement03 },
    { name: "Archive", icon: Archive },
    { name: "Arrow Block Down", icon: ArrowBlockDown },
    { name: "Arrow Block Left", icon: ArrowBlockLeft },
    { name: "Arrow Block Right", icon: ArrowBlockRight },
    { name: "Arrow Block Up", icon: ArrowBlockUp },
    { name: "Arrow Circle Broken Down", icon: ArrowCircleBrokenDown },
    { name: "Arrow Circle Broken Down Left", icon: ArrowCircleBrokenDownLeft },
    { name: "Arrow Circle Broken Down Right", icon: ArrowCircleBrokenDownRight },
    { name: "Arrow Circle Broken Left", icon: ArrowCircleBrokenLeft },
    { name: "Arrow Circle Broken Right", icon: ArrowCircleBrokenRight },
    { name: "Arrow Circle Broken Up", icon: ArrowCircleBrokenUp },
    { name: "Arrow Circle Broken Up Left", icon: ArrowCircleBrokenUpLeft },
    { name: "Arrow Circle Broken Up Right", icon: ArrowCircleBrokenUpRight },
    { name: "Arrow Circle Down", icon: ArrowCircleDown },
    { name: "Arrow Circle Down Left", icon: ArrowCircleDownLeft },
    { name: "Arrow Circle Down Right", icon: ArrowCircleDownRight },
    { name: "Arrow Circle Left", icon: ArrowCircleLeft },
    { name: "Arrow Circle Right", icon: ArrowCircleRight },
    { name: "Arrow Circle Up", icon: ArrowCircleUp },
    { name: "Arrow Circle Up Left", icon: ArrowCircleUpLeft },
    { name: "Arrow Circle Up Right", icon: ArrowCircleUpRight },
    { name: "Arrow Down", icon: ArrowDown },
    { name: "Arrow Down Left", icon: ArrowDownLeft },
    { name: "Arrow Down Right", icon: ArrowDownRight },
    { name: "Arrow Left", icon: ArrowLeft },
    { name: "Arrow Narrow Down", icon: ArrowNarrowDown },
    { name: "Arrow Narrow Down Left", icon: ArrowNarrowDownLeft },
    { name: "Arrow Narrow Down Right", icon: ArrowNarrowDownRight },
    { name: "Arrow Narrow Left", icon: ArrowNarrowLeft },
    { name: "Arrow Narrow Right", icon: ArrowNarrowRight },
    { name: "Arrow Narrow Up", icon: ArrowNarrowUp },
    { name: "Arrow Narrow Up Left", icon: ArrowNarrowUpLeft },
    { name: "Arrow Narrow Up Right", icon: ArrowNarrowUpRight },
    { name: "Arrow Next", icon: ArrowNext },
    { name: "Arrow Previous", icon: ArrowPrevious },
    { name: "Arrow Right", icon: ArrowRight },
    { name: "Arrows Down", icon: ArrowsDown },
    { name: "Arrows Left", icon: ArrowsLeft },
    { name: "Arrow Square Down", icon: ArrowSquareDown },
    { name: "Arrow Square Down Left", icon: ArrowSquareDownLeft },
    { name: "Arrow Square Down Right", icon: ArrowSquareDownRight },
    { name: "Arrow Square Left", icon: ArrowSquareLeft },
    { name: "Arrow Square Right", icon: ArrowSquareRight },
    { name: "Arrow Square Up", icon: ArrowSquareUp },
    { name: "Arrow Square Up Left", icon: ArrowSquareUpLeft },
    { name: "Arrow Square Up Right", icon: ArrowSquareUpRight },
    { name: "Arrows Right", icon: ArrowsRight },
    { name: "Arrows Triangle", icon: ArrowsTriangle },
    { name: "Arrows Up", icon: ArrowsUp },
    { name: "Arrow Up", icon: ArrowUp },
    { name: "Arrow Up Left", icon: ArrowUpLeft },
    { name: "Arrow Up Right", icon: ArrowUpRight },
    { name: "Asterisk 01", icon: Asterisk01 },
    { name: "Asterisk 02", icon: Asterisk02 },
    { name: "Atom 01", icon: Atom01 },
    { name: "Atom 02", icon: Atom02 },
    { name: "At Sign", icon: AtSign },
    { name: "Attachment 01", icon: Attachment01 },
    { name: "Attachment 02", icon: Attachment02 },
    { name: "Award 01", icon: Award01 },
    { name: "Award 02", icon: Award02 },
    { name: "Award 03", icon: Award03 },
    { name: "Award 04", icon: Award04 },
    { name: "Award 05", icon: Award05 },
    { name: "Backpack", icon: Backpack },
    { name: "Bank", icon: Bank },
    { name: "Bank Note 01", icon: BankNote01 },
    { name: "Bank Note 02", icon: BankNote02 },
    { name: "Bank Note 03", icon: BankNote03 },
    { name: "Bar Chart 01", icon: BarChart01 },
    { name: "Bar Chart 02", icon: BarChart02 },
    { name: "Bar Chart 03", icon: BarChart03 },
    { name: "Bar Chart 04", icon: BarChart04 },
    { name: "Bar Chart 05", icon: BarChart05 },
    { name: "Bar Chart 06", icon: BarChart06 },
    { name: "Bar Chart 07", icon: BarChart07 },
    { name: "Bar Chart 08", icon: BarChart08 },
    { name: "Bar Chart 09", icon: BarChart09 },
    { name: "Bar Chart 10", icon: BarChart10 },
    { name: "Bar Chart 11", icon: BarChart11 },
    { name: "Bar Chart 12", icon: BarChart12 },
    { name: "Bar Chart Circle 01", icon: BarChartCircle01 },
    { name: "Bar Chart Circle 02", icon: BarChartCircle02 },
    { name: "Bar Chart Circle 03", icon: BarChartCircle03 },
    { name: "Bar Chart Square 01", icon: BarChartSquare01 },
    { name: "Bar Chart Square 02", icon: BarChartSquare02 },
    { name: "Bar Chart Square 03", icon: BarChartSquare03 },
    { name: "Bar Chart Square Down", icon: BarChartSquareDown },
    { name: "Bar Chart Square Minus", icon: BarChartSquareMinus },
    { name: "Bar Chart Square Plus", icon: BarChartSquarePlus },
    { name: "Bar Chart Square Up", icon: BarChartSquareUp },
    { name: "Bar Line Chart", icon: BarLineChart },
    { name: "Battery Charging 01", icon: BatteryCharging01 },
    { name: "Battery Charging 02", icon: BatteryCharging02 },
    { name: "Battery Empty", icon: BatteryEmpty },
    { name: "Battery Full", icon: BatteryFull },
    { name: "Battery Low", icon: BatteryLow },
    { name: "Battery Mid", icon: BatteryMid },
    { name: "Beaker 01", icon: Beaker01 },
    { name: "Beaker 02", icon: Beaker02 },
    { name: "Bell 01", icon: Bell01 },
    { name: "Bell 02", icon: Bell02 },
    { name: "Bell 03", icon: Bell03 },
    { name: "Bell 04", icon: Bell04 },
    { name: "Bell Minus", icon: BellMinus },
    { name: "Bell Off 01", icon: BellOff01 },
    { name: "Bell Off 02", icon: BellOff02 },
    { name: "Bell Off 03", icon: BellOff03 },
    { name: "Bell Plus", icon: BellPlus },
    { name: "Bell Ringing 01", icon: BellRinging01 },
    { name: "Bell Ringing 02", icon: BellRinging02 },
    { name: "Bell Ringing 03", icon: BellRinging03 },
    { name: "Bell Ringing 04", icon: BellRinging04 },
    { name: "Bezier Curve 01", icon: BezierCurve01 },
    { name: "Bezier Curve 02", icon: BezierCurve02 },
    { name: "Bezier Curve 03", icon: BezierCurve03 },
    { name: "Bluetooth Connect", icon: BluetoothConnect },
    { name: "Bluetooth Off", icon: BluetoothOff },
    { name: "Bluetooth On", icon: BluetoothOn },
    { name: "Bluetooth Signal", icon: BluetoothSignal },
    { name: "Bold 01", icon: Bold01 },
    { name: "Bold 02", icon: Bold02 },
    { name: "Bold Square", icon: BoldSquare },
    { name: "Book Closed", icon: BookClosed },
    { name: "Bookmark", icon: Bookmark },
    { name: "Bookmark Add", icon: BookmarkAdd },
    { name: "Bookmark Check", icon: BookmarkCheck },
    { name: "Bookmark Minus", icon: BookmarkMinus },
    { name: "Bookmark X", icon: BookmarkX },
    { name: "Book Open 01", icon: BookOpen01 },
    { name: "Book Open 02", icon: BookOpen02 },
    { name: "Box", icon: Box },
    { name: "Brackets", icon: Brackets },
    { name: "Brackets Check", icon: BracketsCheck },
    { name: "Brackets Ellipses", icon: BracketsEllipses },
    { name: "Brackets Minus", icon: BracketsMinus },
    { name: "Brackets Plus", icon: BracketsPlus },
    { name: "Brackets Slash", icon: BracketsSlash },
    { name: "Brackets X", icon: BracketsX },
    { name: "Briefcase 01", icon: Briefcase01 },
    { name: "Briefcase 02", icon: Briefcase02 },
    { name: "Browser", icon: Browser },
    { name: "Brush 01", icon: Brush01 },
    { name: "Brush 02", icon: Brush02 },
    { name: "Brush 03", icon: Brush03 },
    { name: "Building 01", icon: Building01 },
    { name: "Building 02", icon: Building02 },
    { name: "Building 03", icon: Building03 },
    { name: "Building 04", icon: Building04 },
    { name: "Building 05", icon: Building05 },
    { name: "Building 06", icon: Building06 },
    { name: "Building 07", icon: Building07 },
    { name: "Building 08", icon: Building08 },
    { name: "Bus", icon: Bus },
    { name: "Calculator", icon: Calculator },
    { name: "Calendar", icon: Calendar },
    { name: "Calendar Check 01", icon: CalendarCheck01 },
    { name: "Calendar Check 02", icon: CalendarCheck02 },
    { name: "Calendar Date", icon: CalendarDate },
    { name: "Calendar Heart 01", icon: CalendarHeart01 },
    { name: "Calendar Heart 02", icon: CalendarHeart02 },
    { name: "Calendar Minus 01", icon: CalendarMinus01 },
    { name: "Calendar Minus 02", icon: CalendarMinus02 },
    { name: "Calendar Plus 01", icon: CalendarPlus01 },
    { name: "Calendar Plus 02", icon: CalendarPlus02 },
    { name: "Camera 01", icon: Camera01 },
    { name: "Camera 02", icon: Camera02 },
    { name: "Camera 03", icon: Camera03 },
    { name: "Camera Lens", icon: CameraLens },
    { name: "Camera Off", icon: CameraOff },
    { name: "Camera Plus", icon: CameraPlus },
    { name: "Car 01", icon: Car01 },
    { name: "Car 02", icon: Car02 },
    { name: "Certificate 01", icon: Certificate01 },
    { name: "Certificate 02", icon: Certificate02 },
    { name: "Chart Breakout Circle", icon: ChartBreakoutCircle },
    { name: "Chart Breakout Square", icon: ChartBreakoutSquare },
    { name: "Check", icon: Check },
    { name: "Check Circle", icon: CheckCircle },
    { name: "Check Circle Broken", icon: CheckCircleBroken },
    { name: "Check Done 01", icon: CheckDone01 },
    { name: "Check Done 02", icon: CheckDone02 },
    { name: "Check Heart", icon: CheckHeart },
    { name: "Check Square", icon: CheckSquare },
    { name: "Check Square Broken", icon: CheckSquareBroken },
    { name: "Check Verified 01", icon: CheckVerified01 },
    { name: "Check Verified 02", icon: CheckVerified02 },
    { name: "Check Verified 03", icon: CheckVerified03 },
    { name: "Chevron Down", icon: ChevronDown },
    { name: "Chevron Down Double", icon: ChevronDownDouble },
    { name: "Chevron Left", icon: ChevronLeft },
    { name: "Chevron Left Double", icon: ChevronLeftDouble },
    { name: "Chevron Next", icon: ChevronNext },
    { name: "Chevron Next Double", icon: ChevronNextDouble },
    { name: "Chevron Previous", icon: ChevronPrevious },
    { name: "Chevron Previous Double", icon: ChevronPreviousDouble },
    { name: "Chevron Right", icon: ChevronRight },
    { name: "Chevron Right Double", icon: ChevronRightDouble },
    { name: "Chevron Selector Horizontal", icon: ChevronSelectorHorizontal },
    { name: "Chevron Selector Vertical", icon: ChevronSelectorVertical },
    { name: "Chevron Up", icon: ChevronUp },
    { name: "Chevron Up Double", icon: ChevronUpDouble },
    { name: "Chrome Cast", icon: ChromeCast },
    { name: "Circle", icon: Circle },
    { name: "Circle Cut", icon: CircleCut },
    { name: "Clapperboard", icon: Clapperboard },
    { name: "Clipboard", icon: Clipboard },
    { name: "Clipboard Attachment", icon: ClipboardAttachment },
    { name: "Clipboard Check", icon: ClipboardCheck },
    { name: "Clipboard Download", icon: ClipboardDownload },
    { name: "Clipboard Minus", icon: ClipboardMinus },
    { name: "Clipboard Plus", icon: ClipboardPlus },
    { name: "Clipboard X", icon: ClipboardX },
    { name: "Clock", icon: Clock },
    { name: "Clock Check", icon: ClockCheck },
    { name: "Clock Fast Forward", icon: ClockFastForward },
    { name: "Clock Plus", icon: ClockPlus },
    { name: "Clock Refresh", icon: ClockRefresh },
    { name: "Clock Rewind", icon: ClockRewind },
    { name: "Clock Snooze", icon: ClockSnooze },
    { name: "Clock Stopwatch", icon: ClockStopwatch },
    { name: "Cloud 01", icon: Cloud01 },
    { name: "Cloud 02", icon: Cloud02 },
    { name: "Cloud 03", icon: Cloud03 },
    { name: "Cloud Blank 01", icon: CloudBlank01 },
    { name: "Cloud Blank 02", icon: CloudBlank02 },
    { name: "Cloud Lightning", icon: CloudLightning },
    { name: "Cloud Moon", icon: CloudMoon },
    { name: "Cloud Off", icon: CloudOff },
    { name: "Cloud Raining 01", icon: CloudRaining01 },
    { name: "Cloud Raining 02", icon: CloudRaining02 },
    { name: "Cloud Raining 03", icon: CloudRaining03 },
    { name: "Cloud Raining 04", icon: CloudRaining04 },
    { name: "Cloud Raining 05", icon: CloudRaining05 },
    { name: "Cloud Raining 06", icon: CloudRaining06 },
    { name: "Cloud Snowing 01", icon: CloudSnowing01 },
    { name: "Cloud Snowing 02", icon: CloudSnowing02 },
    { name: "Cloud Sun 01", icon: CloudSun01 },
    { name: "Cloud Sun 02", icon: CloudSun02 },
    { name: "Cloud Sun 03", icon: CloudSun03 },
    { name: "Code 01", icon: Code01 },
    { name: "Code 02", icon: Code02 },
    { name: "Code Browser", icon: CodeBrowser },
    { name: "Code Circle 01", icon: CodeCircle01 },
    { name: "Code Circle 02", icon: CodeCircle02 },
    { name: "Code Circle 03", icon: CodeCircle03 },
    { name: "Codepen", icon: Codepen },
    { name: "Code Snippet 01", icon: CodeSnippet01 },
    { name: "Code Snippet 02", icon: CodeSnippet02 },
    { name: "Code Square 01", icon: CodeSquare01 },
    { name: "Code Square 02", icon: CodeSquare02 },
    { name: "Coins 01", icon: Coins01 },
    { name: "Coins 02", icon: Coins02 },
    { name: "Coins 03", icon: Coins03 },
    { name: "Coins 04", icon: Coins04 },
    { name: "Coins Hand", icon: CoinsHand },
    { name: "Coins Stacked 01", icon: CoinsStacked01 },
    { name: "Coins Stacked 02", icon: CoinsStacked02 },
    { name: "Coins Stacked 03", icon: CoinsStacked03 },
    { name: "Coins Stacked 04", icon: CoinsStacked04 },
    { name: "Coins Swap 01", icon: CoinsSwap01 },
    { name: "Coins Swap 02", icon: CoinsSwap02 },
    { name: "Colors", icon: Colors },
    { name: "Colors 1", icon: Colors1 },
    { name: "Columns 01", icon: Columns01 },
    { name: "Columns 02", icon: Columns02 },
    { name: "Columns 03", icon: Columns03 },
    { name: "Command", icon: Command },
    { name: "Compass", icon: Compass },
    { name: "Compass 01", icon: Compass01 },
    { name: "Compass 02", icon: Compass02 },
    { name: "Compass 03", icon: Compass03 },
    { name: "Container", icon: Container },
    { name: "Contrast 01", icon: Contrast01 },
    { name: "Contrast 02", icon: Contrast02 },
    { name: "Contrast 03", icon: Contrast03 },
    { name: "Copy 01", icon: Copy01 },
    { name: "Copy 02", icon: Copy02 },
    { name: "Copy 03", icon: Copy03 },
    { name: "Copy 04", icon: Copy04 },
    { name: "Copy 05", icon: Copy05 },
    { name: "Copy 06", icon: Copy06 },
    { name: "Copy 07", icon: Copy07 },
    { name: "Corner Down Left", icon: CornerDownLeft },
    { name: "Corner Down Right", icon: CornerDownRight },
    { name: "Corner Left Down", icon: CornerLeftDown },
    { name: "Corner Left Up", icon: CornerLeftUp },
    { name: "Corner Right Down", icon: CornerRightDown },
    { name: "Corner Right Up", icon: CornerRightUp },
    { name: "Corner Up Left", icon: CornerUpLeft },
    { name: "Corner Up Right", icon: CornerUpRight },
    { name: "Cpu Chip 01", icon: CpuChip01 },
    { name: "Cpu Chip 02", icon: CpuChip02 },
    { name: "Credit Card 01", icon: CreditCard01 },
    { name: "Credit Card 02", icon: CreditCard02 },
    { name: "Credit Card Check", icon: CreditCardCheck },
    { name: "Credit Card Down", icon: CreditCardDown },
    { name: "Credit Card Download", icon: CreditCardDownload },
    { name: "Credit Card Edit", icon: CreditCardEdit },
    { name: "Credit Card Lock", icon: CreditCardLock },
    { name: "Credit Card Minus", icon: CreditCardMinus },
    { name: "Credit Card Plus", icon: CreditCardPlus },
    { name: "Credit Card Refresh", icon: CreditCardRefresh },
    { name: "Credit Card Search", icon: CreditCardSearch },
    { name: "Credit Card Shield", icon: CreditCardShield },
    { name: "Credit Card Up", icon: CreditCardUp },
    { name: "Credit Card Upload", icon: CreditCardUpload },
    { name: "Credit Card X", icon: CreditCardX },
    { name: "Crop 01", icon: Crop01 },
    { name: "Crop 02", icon: Crop02 },
    { name: "Cryptocurrency 01", icon: Cryptocurrency01 },
    { name: "Cryptocurrency 02", icon: Cryptocurrency02 },
    { name: "Cryptocurrency 03", icon: Cryptocurrency03 },
    { name: "Cryptocurrency 04", icon: Cryptocurrency04 },
    { name: "Cube 01", icon: Cube01 },
    { name: "Cube 02", icon: Cube02 },
    { name: "Cube 03", icon: Cube03 },
    { name: "Cube 04", icon: Cube04 },
    { name: "Cube Outline", icon: CubeOutline },
    { name: "Currency Bitcoin", icon: CurrencyBitcoin },
    { name: "Currency Bitcoin Circle", icon: CurrencyBitcoinCircle },
    { name: "Currency Dollar", icon: CurrencyDollar },
    { name: "Currency Dollar Circle", icon: CurrencyDollarCircle },
    { name: "Currency Ethereum", icon: CurrencyEthereum },
    { name: "Currency Ethereum Circle", icon: CurrencyEthereumCircle },
    { name: "Currency Euro", icon: CurrencyEuro },
    { name: "Currency Euro Circle", icon: CurrencyEuroCircle },
    { name: "Currency Pound", icon: CurrencyPound },
    { name: "Currency Pound Circle", icon: CurrencyPoundCircle },
    { name: "Currency Ruble", icon: CurrencyRuble },
    { name: "Currency Ruble Circle", icon: CurrencyRubleCircle },
    { name: "Currency Rupee", icon: CurrencyRupee },
    { name: "Currency Rupee Circle", icon: CurrencyRupeeCircle },
    { name: "Currency Yen", icon: CurrencyYen },
    { name: "Currency Yen Circle", icon: CurrencyYenCircle },
    { name: "Cursor 01", icon: Cursor01 },
    { name: "Cursor 02", icon: Cursor02 },
    { name: "Cursor 03", icon: Cursor03 },
    { name: "Cursor 04", icon: Cursor04 },
    { name: "Cursor Box", icon: CursorBox },
    { name: "Cursor Click 01", icon: CursorClick01 },
    { name: "Cursor Click 02", icon: CursorClick02 },
    { name: "Data", icon: Data },
    { name: "Database 01", icon: Database01 },
    { name: "Database 02", icon: Database02 },
    { name: "Database 03", icon: Database03 },
    { name: "Dataflow 01", icon: Dataflow01 },
    { name: "Dataflow 02", icon: Dataflow02 },
    { name: "Dataflow 03", icon: Dataflow03 },
    { name: "Dataflow 04", icon: Dataflow04 },
    { name: "Delete", icon: Delete },
    { name: "Diamond 01", icon: Diamond01 },
    { name: "Diamond 02", icon: Diamond02 },
    { name: "Dice 1", icon: Dice1 },
    { name: "Dice 2", icon: Dice2 },
    { name: "Dice 3", icon: Dice3 },
    { name: "Dice 4", icon: Dice4 },
    { name: "Dice 5", icon: Dice5 },
    { name: "Dice 6", icon: Dice6 },
    { name: "Disc 01", icon: Disc01 },
    { name: "Disc 02", icon: Disc02 },
    { name: "Distribute Spacing Horizontal", icon: DistributeSpacingHorizontal },
    { name: "Distribute Spacing Vertical", icon: DistributeSpacingVertical },
    { name: "Divide 01", icon: Divide01 },
    { name: "Divide 02", icon: Divide02 },
    { name: "Divide 03", icon: Divide03 },
    { name: "Divider", icon: Divider },
    { name: "Dotpoints 01", icon: Dotpoints01 },
    { name: "Dotpoints 02", icon: Dotpoints02 },
    { name: "Dots Grid", icon: DotsGrid },
    { name: "Dots Horizontal", icon: DotsHorizontal },
    { name: "Dots Vertical", icon: DotsVertical },
    { name: "Download 01", icon: Download01 },
    { name: "Download 02", icon: Download02 },
    { name: "Download 03", icon: Download03 },
    { name: "Download 04", icon: Download04 },
    { name: "Download Cloud 01", icon: DownloadCloud01 },
    { name: "Download Cloud 02", icon: DownloadCloud02 },
    { name: "Drop", icon: Drop },
    { name: "Droplets 01", icon: Droplets01 },
    { name: "Droplets 02", icon: Droplets02 },
    { name: "Droplets 03", icon: Droplets03 },
    { name: "Dropper", icon: Dropper },
    { name: "Edit 01", icon: Edit01 },
    { name: "Edit 02", icon: Edit02 },
    { name: "Edit 03", icon: Edit03 },
    { name: "Edit 04", icon: Edit04 },
    { name: "Edit 05", icon: Edit05 },
    { name: "Equal", icon: Equal },
    { name: "Equal Not", icon: EqualNot },
    { name: "Eraser", icon: Eraser },
    { name: "Expand 01", icon: Expand01 },
    { name: "Expand 02", icon: Expand02 },
    { name: "Expand 03", icon: Expand03 },
    { name: "Expand 04", icon: Expand04 },
    { name: "Expand 05", icon: Expand05 },
    { name: "Expand 06", icon: Expand06 },
    { name: "Eye", icon: Eye },
    { name: "Eye Off", icon: EyeOff },
    { name: "Face Content", icon: FaceContent },
    { name: "Face Frown", icon: FaceFrown },
    { name: "Face Happy", icon: FaceHappy },
    { name: "Face Id", icon: FaceId },
    { name: "Face Id Square", icon: FaceIdSquare },
    { name: "Face Neutral", icon: FaceNeutral },
    { name: "Face Sad", icon: FaceSad },
    { name: "Face Smile", icon: FaceSmile },
    { name: "Face Wink", icon: FaceWink },
    { name: "Fast Backward", icon: FastBackward },
    { name: "Fast Forward", icon: FastForward },
    { name: "Feather", icon: Feather },
    { name: "Figma", icon: Figma },
    { name: "File 01", icon: File01 },
    { name: "File 02", icon: File02 },
    { name: "File 03", icon: File03 },
    { name: "File 04", icon: File04 },
    { name: "File 05", icon: File05 },
    { name: "File 06", icon: File06 },
    { name: "File 07", icon: File07 },
    { name: "File Attachment 01", icon: FileAttachment01 },
    { name: "File Attachment 02", icon: FileAttachment02 },
    { name: "File Attachment 03", icon: FileAttachment03 },
    { name: "File Attachment 04", icon: FileAttachment04 },
    { name: "File Attachment 05", icon: FileAttachment05 },
    { name: "File Check 01", icon: FileCheck01 },
    { name: "File Check 02", icon: FileCheck02 },
    { name: "File Check 03", icon: FileCheck03 },
    { name: "File Code 01", icon: FileCode01 },
    { name: "File Code 02", icon: FileCode02 },
    { name: "File Download 01", icon: FileDownload01 },
    { name: "File Download 02", icon: FileDownload02 },
    { name: "File Download 03", icon: FileDownload03 },
    { name: "File Heart 01", icon: FileHeart01 },
    { name: "File Heart 02", icon: FileHeart02 },
    { name: "File Heart 03", icon: FileHeart03 },
    { name: "File Lock 01", icon: FileLock01 },
    { name: "File Lock 02", icon: FileLock02 },
    { name: "File Lock 03", icon: FileLock03 },
    { name: "File Minus 01", icon: FileMinus01 },
    { name: "File Minus 02", icon: FileMinus02 },
    { name: "File Minus 03", icon: FileMinus03 },
    { name: "File Plus 01", icon: FilePlus01 },
    { name: "File Plus 02", icon: FilePlus02 },
    { name: "File Plus 03", icon: FilePlus03 },
    { name: "File Question 01", icon: FileQuestion01 },
    { name: "File Question 02", icon: FileQuestion02 },
    { name: "File Question 03", icon: FileQuestion03 },
    { name: "File Search 01", icon: FileSearch01 },
    { name: "File Search 02", icon: FileSearch02 },
    { name: "File Search 03", icon: FileSearch03 },
    { name: "File Shield 01", icon: FileShield01 },
    { name: "File Shield 02", icon: FileShield02 },
    { name: "File Shield 03", icon: FileShield03 },
    { name: "File X 01", icon: FileX01 },
    { name: "File X 02", icon: FileX02 },
    { name: "File X 03", icon: FileX03 },
    { name: "Film 01", icon: Film01 },
    { name: "Film 02", icon: Film02 },
    { name: "Film 03", icon: Film03 },
    { name: "Filter Funnel 01", icon: FilterFunnel01 },
    { name: "Filter Funnel 02", icon: FilterFunnel02 },
    { name: "Filter Lines", icon: FilterLines },
    { name: "Fingerprint 01", icon: Fingerprint01 },
    { name: "Fingerprint 02", icon: Fingerprint02 },
    { name: "Fingerprint 03", icon: Fingerprint03 },
    { name: "Fingerprint 04", icon: Fingerprint04 },
    { name: "Flag 01", icon: Flag01 },
    { name: "Flag 02", icon: Flag02 },
    { name: "Flag 03", icon: Flag03 },
    { name: "Flag 04", icon: Flag04 },
    { name: "Flag 05", icon: Flag05 },
    { name: "Flag 06", icon: Flag06 },
    { name: "Flash", icon: Flash },
    { name: "Flash Off", icon: FlashOff },
    { name: "Flex Align Bottom", icon: FlexAlignBottom },
    { name: "Flex Align Left", icon: FlexAlignLeft },
    { name: "Flex Align Right", icon: FlexAlignRight },
    { name: "Flex Align Top", icon: FlexAlignTop },
    { name: "Flip Backward", icon: FlipBackward },
    { name: "Flip Forward", icon: FlipForward },
    { name: "Folder", icon: Folder },
    { name: "Folder Check", icon: FolderCheck },
    { name: "Folder Closed", icon: FolderClosed },
    { name: "Folder Code", icon: FolderCode },
    { name: "Folder Download", icon: FolderDownload },
    { name: "Folder Lock", icon: FolderLock },
    { name: "Folder Minus", icon: FolderMinus },
    { name: "Folder Plus", icon: FolderPlus },
    { name: "Folder Question", icon: FolderQuestion },
    { name: "Folder Search", icon: FolderSearch },
    { name: "Folder Shield", icon: FolderShield },
    { name: "Folder X", icon: FolderX },
    { name: "Framer", icon: Framer },
    { name: "Gaming Pad 01", icon: GamingPad01 },
    { name: "Gaming Pad 02", icon: GamingPad02 },
    { name: "Gift 01", icon: Gift01 },
    { name: "Gift 02", icon: Gift02 },
    { name: "Git Branch 01", icon: GitBranch01 },
    { name: "Git Branch 02", icon: GitBranch02 },
    { name: "Git Commit", icon: GitCommit },
    { name: "Git Merge", icon: GitMerge },
    { name: "Git Pull Request", icon: GitPullRequest },
    { name: "Glasses 01", icon: Glasses01 },
    { name: "Glasses 02", icon: Glasses02 },
    { name: "Globe 01", icon: Globe01 },
    { name: "Globe 02", icon: Globe02 },
    { name: "Globe 03", icon: Globe03 },
    { name: "Globe 04", icon: Globe04 },
    { name: "Globe 05", icon: Globe05 },
    { name: "Globe 06", icon: Globe06 },
    { name: "Globe Slated 01", icon: GlobeSlated01 },
    { name: "Globe Slated 02", icon: GlobeSlated02 },
    { name: "Google Chrome", icon: GoogleChrome },
    { name: "Graduation Hat 01", icon: GraduationHat01 },
    { name: "Graduation Hat 02", icon: GraduationHat02 },
    { name: "Grid 01", icon: Grid01 },
    { name: "Grid 02", icon: Grid02 },
    { name: "Grid 03", icon: Grid03 },
    { name: "Grid Dots Blank", icon: GridDotsBlank },
    { name: "Grid Dots Bottom", icon: GridDotsBottom },
    { name: "Grid Dots Horizontal Center", icon: GridDotsHorizontalCenter },
    { name: "Grid Dots Left", icon: GridDotsLeft },
    { name: "Grid Dots Outer", icon: GridDotsOuter },
    { name: "Grid Dots Right", icon: GridDotsRight },
    { name: "Grid Dots Top", icon: GridDotsTop },
    { name: "Grid Dots Vertical Center", icon: GridDotsVerticalCenter },
    { name: "Hand", icon: Hand },
    { name: "Hard Drive", icon: HardDrive },
    { name: "Hash 01", icon: Hash01 },
    { name: "Hash 02", icon: Hash02 },
    { name: "Heading 01", icon: Heading01 },
    { name: "Heading 02", icon: Heading02 },
    { name: "Heading Square", icon: HeadingSquare },
    { name: "Headphones 01", icon: Headphones01 },
    { name: "Headphones 02", icon: Headphones02 },
    { name: "Heart", icon: Heart },
    { name: "Heart Circle", icon: HeartCircle },
    { name: "Heart Hand", icon: HeartHand },
    { name: "Heart Hexagon", icon: HeartHexagon },
    { name: "Heart Octagon", icon: HeartOctagon },
    { name: "Heart Rounded", icon: HeartRounded },
    { name: "Hearts", icon: Hearts },
    { name: "Heart Square", icon: HeartSquare },
    { name: "Help Circle", icon: HelpCircle },
    { name: "Help Octagon", icon: HelpOctagon },
    { name: "Help Octagon 1", icon: HelpOctagon1 },
    { name: "Help Square", icon: HelpSquare },
    { name: "Hexagon 01", icon: Hexagon01 },
    { name: "Hexagon 02", icon: Hexagon02 },
    { name: "Home 01", icon: Home01 },
    { name: "Home 02", icon: Home02 },
    { name: "Home 03", icon: Home03 },
    { name: "Home 04", icon: Home04 },
    { name: "Home 05", icon: Home05 },
    { name: "Home Line", icon: HomeLine },
    { name: "Home Smile", icon: HomeSmile },
    { name: "Horizontal Bar Chart 01", icon: HorizontalBarChart01 },
    { name: "Horizontal Bar Chart 02", icon: HorizontalBarChart02 },
    { name: "Horizontal Bar Chart 03", icon: HorizontalBarChart03 },
    { name: "Hourglass 01", icon: Hourglass01 },
    { name: "Hourglass 02", icon: Hourglass02 },
    { name: "Hourglass 03", icon: Hourglass03 },
    { name: "Hurricane 01", icon: Hurricane01 },
    { name: "Hurricane 02", icon: Hurricane02 },
    { name: "Hurricane 03", icon: Hurricane03 },
    { name: "Image 01", icon: Image01 },
    { name: "Image 02", icon: Image02 },
    { name: "Image 03", icon: Image03 },
    { name: "Image 04", icon: Image04 },
    { name: "Image 05", icon: Image05 },
    { name: "Image Check", icon: ImageCheck },
    { name: "Image Down", icon: ImageDown },
    { name: "Image Indent Left", icon: ImageIndentLeft },
    { name: "Image Indent Right", icon: ImageIndentRight },
    { name: "Image Left", icon: ImageLeft },
    { name: "Image Plus", icon: ImagePlus },
    { name: "Image Right", icon: ImageRight },
    { name: "Image Up", icon: ImageUp },
    { name: "Image User", icon: ImageUser },
    { name: "Image User Check", icon: ImageUserCheck },
    { name: "Image User Down", icon: ImageUserDown },
    { name: "Image User Left", icon: ImageUserLeft },
    { name: "Image User Plus", icon: ImageUserPlus },
    { name: "Image User Right", icon: ImageUserRight },
    { name: "Image User Up", icon: ImageUserUp },
    { name: "Image User X", icon: ImageUserX },
    { name: "Image X", icon: ImageX },
    { name: "Inbox 01", icon: Inbox01 },
    { name: "Inbox 02", icon: Inbox02 },
    { name: "Infinity", icon: Infinity },
    { name: "Info Circle", icon: InfoCircle },
    { name: "Info Hexagon", icon: InfoHexagon },
    { name: "Info Octagon", icon: InfoOctagon },
    { name: "Info Square", icon: InfoSquare },
    { name: "Intersect Circle", icon: IntersectCircle },
    { name: "Intersect Square", icon: IntersectSquare },
    { name: "Italic 01", icon: Italic01 },
    { name: "Italic 02", icon: Italic02 },
    { name: "Italic Square", icon: ItalicSquare },
    { name: "Key 01", icon: Key01 },
    { name: "Key 02", icon: Key02 },
    { name: "Keyboard 01", icon: Keyboard01 },
    { name: "Keyboard 02", icon: Keyboard02 },
    { name: "Laptop 01", icon: Laptop01 },
    { name: "Laptop 02", icon: Laptop02 },
    { name: "Layer Single", icon: LayerSingle },
    { name: "Layers Three 01", icon: LayersThree01 },
    { name: "Layers Three 02", icon: LayersThree02 },
    { name: "Layers Two 01", icon: LayersTwo01 },
    { name: "Layers Two 02", icon: LayersTwo02 },
    { name: "Layout Alt 01", icon: LayoutAlt01 },
    { name: "Layout Alt 02", icon: LayoutAlt02 },
    { name: "Layout Alt 03", icon: LayoutAlt03 },
    { name: "Layout Alt 04", icon: LayoutAlt04 },
    { name: "Layout Bottom", icon: LayoutBottom },
    { name: "Layout Grid 01", icon: LayoutGrid01 },
    { name: "Layout Grid 02", icon: LayoutGrid02 },
    { name: "Layout Left", icon: LayoutLeft },
    { name: "Layout Right", icon: LayoutRight },
    { name: "Layout Top", icon: LayoutTop },
    { name: "Left Indent 01", icon: LeftIndent01 },
    { name: "Left Indent 02", icon: LeftIndent02 },
    { name: "Letter Spacing 01", icon: LetterSpacing01 },
    { name: "Letter Spacing 02", icon: LetterSpacing02 },
    { name: "Life Buoy 01", icon: LifeBuoy01 },
    { name: "Life Buoy 02", icon: LifeBuoy02 },
    { name: "Lightbulb 01", icon: Lightbulb01 },
    { name: "Lightbulb 02", icon: Lightbulb02 },
    { name: "Lightbulb 03", icon: Lightbulb03 },
    { name: "Lightbulb 04", icon: Lightbulb04 },
    { name: "Lightbulb 05", icon: Lightbulb05 },
    { name: "Lightning 01", icon: Lightning01 },
    { name: "Lightning 02", icon: Lightning02 },
    { name: "Line Chart Down 01", icon: LineChartDown01 },
    { name: "Line Chart Down 02", icon: LineChartDown02 },
    { name: "Line Chart Down 03", icon: LineChartDown03 },
    { name: "Line Chart Down 04", icon: LineChartDown04 },
    { name: "Line Chart Down 05", icon: LineChartDown05 },
    { name: "Line Chart Up 01", icon: LineChartUp01 },
    { name: "Line Chart Up 02", icon: LineChartUp02 },
    { name: "Line Chart Up 03", icon: LineChartUp03 },
    { name: "Line Chart Up 04", icon: LineChartUp04 },
    { name: "Line Chart Up 05", icon: LineChartUp05 },
    { name: "Line Height", icon: LineHeight },
    { name: "Link 01", icon: Link01 },
    { name: "Link 02", icon: Link02 },
    { name: "Link 03", icon: Link03 },
    { name: "Link 04", icon: Link04 },
    { name: "Link 05", icon: Link05 },
    { name: "Link Broken 01", icon: LinkBroken01 },
    { name: "Link Broken 02", icon: LinkBroken02 },
    { name: "Link External 01", icon: LinkExternal01 },
    { name: "Link External 02", icon: LinkExternal02 },
    { name: "List", icon: List },
    { name: "Loading 01", icon: Loading01 },
    { name: "Loading 02", icon: Loading02 },
    { name: "Loading 03", icon: Loading03 },
    { name: "Lock 01", icon: Lock01 },
    { name: "Lock 02", icon: Lock02 },
    { name: "Lock 03", icon: Lock03 },
    { name: "Lock 04", icon: Lock04 },
    { name: "Lock Keyhole Circle", icon: LockKeyholeCircle },
    { name: "Lock Keyhole Square", icon: LockKeyholeSquare },
    { name: "Lock Unlocked 01", icon: LockUnlocked01 },
    { name: "Lock Unlocked 02", icon: LockUnlocked02 },
    { name: "Lock Unlocked 03", icon: LockUnlocked03 },
    { name: "Lock Unlocked 04", icon: LockUnlocked04 },
    { name: "Log In 01", icon: LogIn01 },
    { name: "Log In 02", icon: LogIn02 },
    { name: "Log In 03", icon: LogIn03 },
    { name: "Log In 04", icon: LogIn04 },
    { name: "Log Out 01", icon: LogOut01 },
    { name: "Log Out 02", icon: LogOut02 },
    { name: "Log Out 03", icon: LogOut03 },
    { name: "Log Out 04", icon: LogOut04 },
    { name: "Luggage 01", icon: Luggage01 },
    { name: "Luggage 02", icon: Luggage02 },
    { name: "Luggage 03", icon: Luggage03 },
    { name: "Magic Wand 01", icon: MagicWand01 },
    { name: "Magic Wand 02", icon: MagicWand02 },
    { name: "Mail 01", icon: Mail01 },
    { name: "Mail 02", icon: Mail02 },
    { name: "Mail 03", icon: Mail03 },
    { name: "Mail 04", icon: Mail04 },
    { name: "Mail 05", icon: Mail05 },
    { name: "Map 01", icon: Map01 },
    { name: "Map 02", icon: Map02 },
    { name: "Mark", icon: Mark },
    { name: "Marker Pin 01", icon: MarkerPin01 },
    { name: "Marker Pin 02", icon: MarkerPin02 },
    { name: "Marker Pin 03", icon: MarkerPin03 },
    { name: "Marker Pin 04", icon: MarkerPin04 },
    { name: "Marker Pin 05", icon: MarkerPin05 },
    { name: "Marker Pin 06", icon: MarkerPin06 },
    { name: "Maximize 01", icon: Maximize01 },
    { name: "Maximize 02", icon: Maximize02 },
    { name: "Medical Circle", icon: MedicalCircle },
    { name: "Medical Cross", icon: MedicalCross },
    { name: "Medical Square", icon: MedicalSquare },
    { name: "Menu 01", icon: Menu01 },
    { name: "Menu 02", icon: Menu02 },
    { name: "Menu 03", icon: Menu03 },
    { name: "Menu 04", icon: Menu04 },
    { name: "Menu 05", icon: Menu05 },
    { name: "Message Alert Circle", icon: MessageAlertCircle },
    { name: "Message Alert Square", icon: MessageAlertSquare },
    { name: "Message Chat Circle", icon: MessageChatCircle },
    { name: "Message Chat Square", icon: MessageChatSquare },
    { name: "Message Check Circle", icon: MessageCheckCircle },
    { name: "Message Check Square", icon: MessageCheckSquare },
    { name: "Message Circle 01", icon: MessageCircle01 },
    { name: "Message Circle 02", icon: MessageCircle02 },
    { name: "Message Dots Circle", icon: MessageDotsCircle },
    { name: "Message Dots Square", icon: MessageDotsSquare },
    { name: "Message Heart Circle", icon: MessageHeartCircle },
    { name: "Message Heart Square", icon: MessageHeartSquare },
    { name: "Message Notification Circle", icon: MessageNotificationCircle },
    { name: "Message Notification Square", icon: MessageNotificationSquare },
    { name: "Message Plus Circle", icon: MessagePlusCircle },
    { name: "Message Plus Square", icon: MessagePlusSquare },
    { name: "Message Question Circle", icon: MessageQuestionCircle },
    { name: "Message Question Square", icon: MessageQuestionSquare },
    { name: "Message Smile Circle", icon: MessageSmileCircle },
    { name: "Message Smile Square", icon: MessageSmileSquare },
    { name: "Message Square 01", icon: MessageSquare01 },
    { name: "Message Square 02", icon: MessageSquare02 },
    { name: "Message Text Circle 01", icon: MessageTextCircle01 },
    { name: "Message Text Circle 02", icon: MessageTextCircle02 },
    { name: "Message Text Square 01", icon: MessageTextSquare01 },
    { name: "Message Text Square 02", icon: MessageTextSquare02 },
    { name: "Message X Circle", icon: MessageXCircle },
    { name: "Message X Square", icon: MessageXSquare },
    { name: "Microphone 01", icon: Microphone01 },
    { name: "Microphone 02", icon: Microphone02 },
    { name: "Microphone Off 01", icon: MicrophoneOff01 },
    { name: "Microphone Off 02", icon: MicrophoneOff02 },
    { name: "Microscope", icon: Microscope },
    { name: "Minimize 01", icon: Minimize01 },
    { name: "Minimize 02", icon: Minimize02 },
    { name: "Minus", icon: Minus },
    { name: "Minus Circle", icon: MinusCircle },
    { name: "Minus Square", icon: MinusSquare },
    { name: "Modem 01", icon: Modem01 },
    { name: "Modem 02", icon: Modem02 },
    { name: "Monitor 01", icon: Monitor01 },
    { name: "Monitor 02", icon: Monitor02 },
    { name: "Monitor 03", icon: Monitor03 },
    { name: "Monitor 04", icon: Monitor04 },
    { name: "Monitor 05", icon: Monitor05 },
    { name: "Moon 01", icon: Moon01 },
    { name: "Moon 02", icon: Moon02 },
    { name: "Moon Eclipse", icon: MoonEclipse },
    { name: "Moon Star", icon: MoonStar },
    { name: "Mouse", icon: Mouse },
    { name: "Move", icon: Move },
    { name: "Music Note 01", icon: MusicNote01 },
    { name: "Music Note 02", icon: MusicNote02 },
    { name: "Music Note Plus", icon: MusicNotePlus },
    { name: "Navigation Pointer 01", icon: NavigationPointer01 },
    { name: "Navigation Pointer 02", icon: NavigationPointer02 },
    { name: "Navigation Pointer Off 01", icon: NavigationPointerOff01 },
    { name: "Navigation Pointer Off 02", icon: NavigationPointerOff02 },
    { name: "Notification Box", icon: NotificationBox },
    { name: "Notification Message", icon: NotificationMessage },
    { name: "Notification Text", icon: NotificationText },
    { name: "Octagon", icon: Octagon },
    { name: "Package", icon: Package },
    { name: "Package Check", icon: PackageCheck },
    { name: "Package Minus", icon: PackageMinus },
    { name: "Package Plus", icon: PackagePlus },
    { name: "Package Search", icon: PackageSearch },
    { name: "Package X", icon: PackageX },
    { name: "Paint", icon: Paint },
    { name: "Paint Pour", icon: PaintPour },
    { name: "Palette", icon: Palette },
    { name: "Paperclip", icon: Paperclip },
    { name: "Paragraph Spacing", icon: ParagraphSpacing },
    { name: "Paragraph Wrap", icon: ParagraphWrap },
    { name: "Passcode", icon: Passcode },
    { name: "Passcode Lock", icon: PasscodeLock },
    { name: "Passport", icon: Passport },
    { name: "Pause Circle", icon: PauseCircle },
    { name: "Pause Square", icon: PauseSquare },
    { name: "Pencil 01", icon: Pencil01 },
    { name: "Pencil 02", icon: Pencil02 },
    { name: "Pencil Line", icon: PencilLine },
    { name: "Pentagon", icon: Pentagon },
    { name: "Pen Tool 01", icon: PenTool01 },
    { name: "Pen Tool 02", icon: PenTool02 },
    { name: "Pen Tool Minus", icon: PenToolMinus },
    { name: "Pen Tool Plus", icon: PenToolPlus },
    { name: "Percent 01", icon: Percent01 },
    { name: "Percent 02", icon: Percent02 },
    { name: "Percent 03", icon: Percent03 },
    { name: "Perspective 01", icon: Perspective01 },
    { name: "Perspective 02", icon: Perspective02 },
    { name: "Phone", icon: Phone },
    { name: "Phone 01", icon: Phone01 },
    { name: "Phone 02", icon: Phone02 },
    { name: "Phone Call 01", icon: PhoneCall01 },
    { name: "Phone Call 02", icon: PhoneCall02 },
    { name: "Phone Hang Up", icon: PhoneHangUp },
    { name: "Phone Incoming 01", icon: PhoneIncoming01 },
    { name: "Phone Incoming 02", icon: PhoneIncoming02 },
    { name: "Phone Outgoing 01", icon: PhoneOutgoing01 },
    { name: "Phone Outgoing 02", icon: PhoneOutgoing02 },
    { name: "Phone Pause", icon: PhonePause },
    { name: "Phone Plus", icon: PhonePlus },
    { name: "Phone X", icon: PhoneX },
    { name: "Pie Chart 01", icon: PieChart01 },
    { name: "Pie Chart 02", icon: PieChart02 },
    { name: "Pie Chart 03", icon: PieChart03 },
    { name: "Pie Chart 04", icon: PieChart04 },
    { name: "Piggy Bank 01", icon: PiggyBank01 },
    { name: "Piggy Bank 02", icon: PiggyBank02 },
    { name: "Pilcrow 01", icon: Pilcrow01 },
    { name: "Pilcrow 02", icon: Pilcrow02 },
    { name: "Pilcrow Square", icon: PilcrowSquare },
    { name: "Pin 01", icon: Pin01 },
    { name: "Pin 02", icon: Pin02 },
    { name: "Placeholder", icon: Placeholder },
    { name: "Plane", icon: Plane },
    { name: "Play", icon: Play },
    { name: "Play Circle", icon: PlayCircle },
    { name: "Play Square", icon: PlaySquare },
    { name: "Plus", icon: Plus },
    { name: "Plus Circle", icon: PlusCircle },
    { name: "Plus Square", icon: PlusSquare },
    { name: "Podcast", icon: Podcast },
    { name: "Power 01", icon: Power01 },
    { name: "Power 02", icon: Power02 },
    { name: "Power 03", icon: Power03 },
    { name: "Presentation Chart 01", icon: PresentationChart01 },
    { name: "Presentation Chart 02", icon: PresentationChart02 },
    { name: "Presentation Chart 03", icon: PresentationChart03 },
    { name: "Printer", icon: Printer },
    { name: "Puzzle Piece 01", icon: PuzzlePiece01 },
    { name: "Puzzle Piece 02", icon: PuzzlePiece02 },
    { name: "Qr Code 01", icon: QrCode01 },
    { name: "Qr Code 02", icon: QrCode02 },
    { name: "Receipt", icon: Receipt },
    { name: "Receipt Check", icon: ReceiptCheck },
    { name: "Recording 01", icon: Recording01 },
    { name: "Recording 02", icon: Recording02 },
    { name: "Recording 03", icon: Recording03 },
    { name: "Reflect 01", icon: Reflect01 },
    { name: "Reflect 02", icon: Reflect02 },
    { name: "Refresh Ccw 01", icon: RefreshCcw01 },
    { name: "Refresh Ccw 02", icon: RefreshCcw02 },
    { name: "Refresh Ccw 03", icon: RefreshCcw03 },
    { name: "Refresh Ccw 04", icon: RefreshCcw04 },
    { name: "Refresh Ccw 05", icon: RefreshCcw05 },
    { name: "Refresh Cw 01", icon: RefreshCw01 },
    { name: "Refresh Cw 02", icon: RefreshCw02 },
    { name: "Refresh Cw 03", icon: RefreshCw03 },
    { name: "Refresh Cw 04", icon: RefreshCw04 },
    { name: "Refresh Cw 05", icon: RefreshCw05 },
    { name: "Repeat 01", icon: Repeat01 },
    { name: "Repeat 02", icon: Repeat02 },
    { name: "Repeat 03", icon: Repeat03 },
    { name: "Repeat 04", icon: Repeat04 },
    { name: "Reverse Left", icon: ReverseLeft },
    { name: "Reverse Right", icon: ReverseRight },
    { name: "Right Indent 01", icon: RightIndent01 },
    { name: "Right Indent 02", icon: RightIndent02 },
    { name: "Rocket 01", icon: Rocket01 },
    { name: "Rocket 02", icon: Rocket02 },
    { name: "Roller Brush", icon: RollerBrush },
    { name: "Route", icon: Route },
    { name: "Rows 01", icon: Rows01 },
    { name: "Rows 02", icon: Rows02 },
    { name: "Rows 03", icon: Rows03 },
    { name: "Rss 01", icon: Rss01 },
    { name: "Rss 02", icon: Rss02 },
    { name: "Ruler", icon: Ruler },
    { name: "Safe", icon: Safe },
    { name: "Sale 01", icon: Sale01 },
    { name: "Sale 02", icon: Sale02 },
    { name: "Sale 03", icon: Sale03 },
    { name: "Sale 04", icon: Sale04 },
    { name: "Save 01", icon: Save01 },
    { name: "Save 02", icon: Save02 },
    { name: "Save 03", icon: Save03 },
    { name: "Scale 01", icon: Scale01 },
    { name: "Scale 02", icon: Scale02 },
    { name: "Scale 03", icon: Scale03 },
    { name: "Scales 01", icon: Scales01 },
    { name: "Scales 02", icon: Scales02 },
    { name: "Scan", icon: Scan },
    { name: "Scissors 01", icon: Scissors01 },
    { name: "Scissors 02", icon: Scissors02 },
    { name: "Scissors Cut 01", icon: ScissorsCut01 },
    { name: "Scissors Cut 02", icon: ScissorsCut02 },
    { name: "Search Lg", icon: SearchLg },
    { name: "Search Md", icon: SearchMd },
    { name: "Search Refraction", icon: SearchRefraction },
    { name: "Search Sm", icon: SearchSm },
    { name: "Send 01", icon: Send01 },
    { name: "Send 02", icon: Send02 },
    { name: "Send 03", icon: Send03 },
    { name: "Server 01", icon: Server01 },
    { name: "Server 02", icon: Server02 },
    { name: "Server 03", icon: Server03 },
    { name: "Server 04", icon: Server04 },
    { name: "Server 05", icon: Server05 },
    { name: "Server 06", icon: Server06 },
    { name: "Settings 01", icon: Settings01 },
    { name: "Settings 02", icon: Settings02 },
    { name: "Settings 03", icon: Settings03 },
    { name: "Settings 04", icon: Settings04 },
    { name: "Share 01", icon: Share01 },
    { name: "Share 02", icon: Share02 },
    { name: "Share 03", icon: Share03 },
    { name: "Share 04", icon: Share04 },
    { name: "Share 05", icon: Share05 },
    { name: "Share 06", icon: Share06 },
    { name: "Share 07", icon: Share07 },
    { name: "Shield 01", icon: Shield01 },
    { name: "Shield 02", icon: Shield02 },
    { name: "Shield 03", icon: Shield03 },
    { name: "Shield Dollar", icon: ShieldDollar },
    { name: "Shield Off", icon: ShieldOff },
    { name: "Shield Plus", icon: ShieldPlus },
    { name: "Shield Tick", icon: ShieldTick },
    { name: "Shield Zap", icon: ShieldZap },
    { name: "Shopping Bag 01", icon: ShoppingBag01 },
    { name: "Shopping Bag 02", icon: ShoppingBag02 },
    { name: "Shopping Bag 03", icon: ShoppingBag03 },
    { name: "Shopping Cart 01", icon: ShoppingCart01 },
    { name: "Shopping Cart 02", icon: ShoppingCart02 },
    { name: "Shopping Cart 03", icon: ShoppingCart03 },
    { name: "Shuffle 01", icon: Shuffle01 },
    { name: "Shuffle 02", icon: Shuffle02 },
    { name: "Signal 01", icon: Signal01 },
    { name: "Signal 02", icon: Signal02 },
    { name: "Signal 03", icon: Signal03 },
    { name: "Simcard", icon: Simcard },
    { name: "Skew", icon: Skew },
    { name: "Skip Back", icon: SkipBack },
    { name: "Skip Forward", icon: SkipForward },
    { name: "Slash Circle 01", icon: SlashCircle01 },
    { name: "Slash Circle 02", icon: SlashCircle02 },
    { name: "Slash Divider", icon: SlashDivider },
    { name: "Slash Octagon", icon: SlashOctagon },
    { name: "Sliders 01", icon: Sliders01 },
    { name: "Sliders 02", icon: Sliders02 },
    { name: "Sliders 03", icon: Sliders03 },
    { name: "Sliders 04", icon: Sliders04 },
    { name: "Snowflake 01", icon: Snowflake01 },
    { name: "Snowflake 02", icon: Snowflake02 },
    { name: "Spacing Height 01", icon: SpacingHeight01 },
    { name: "Spacing Height 02", icon: SpacingHeight02 },
    { name: "Spacing Width 01", icon: SpacingWidth01 },
    { name: "Spacing Width 02", icon: SpacingWidth02 },
    { name: "Speaker 01", icon: Speaker01 },
    { name: "Speaker 02", icon: Speaker02 },
    { name: "Speaker 03", icon: Speaker03 },
    { name: "Speedometer 01", icon: Speedometer01 },
    { name: "Speedometer 02", icon: Speedometer02 },
    { name: "Speedometer 03", icon: Speedometer03 },
    { name: "Speedometer 04", icon: Speedometer04 },
    { name: "Square", icon: Square },
    { name: "Stand", icon: Stand },
    { name: "Star 01", icon: Star01 },
    { name: "Star 02", icon: Star02 },
    { name: "Star 03", icon: Star03 },
    { name: "Star 04", icon: Star04 },
    { name: "Star 05", icon: Star05 },
    { name: "Star 06", icon: Star06 },
    { name: "Star 07", icon: Star07 },
    { name: "Stars 01", icon: Stars01 },
    { name: "Stars 02", icon: Stars02 },
    { name: "Stars 03", icon: Stars03 },
    { name: "Sticker Circle", icon: StickerCircle },
    { name: "Sticker Square", icon: StickerSquare },
    { name: "Stop", icon: Stop },
    { name: "Stop Circle", icon: StopCircle },
    { name: "Stop Square", icon: StopSquare },
    { name: "Strikethrough 01", icon: Strikethrough01 },
    { name: "Strikethrough 02", icon: Strikethrough02 },
    { name: "Strikethrough Square", icon: StrikethroughSquare },
    { name: "Subscript", icon: Subscript },
    { name: "Sun", icon: Sun },
    { name: "Sunrise", icon: Sunrise },
    { name: "Sunset", icon: Sunset },
    { name: "Sun Setting 01", icon: SunSetting01 },
    { name: "Sun Setting 02", icon: SunSetting02 },
    { name: "Sun Setting 03", icon: SunSetting03 },
    { name: "Switch Horizontal 01", icon: SwitchHorizontal01 },
    { name: "Switch Horizontal 02", icon: SwitchHorizontal02 },
    { name: "Switch Vertical 01", icon: SwitchVertical01 },
    { name: "Switch Vertical 02", icon: SwitchVertical02 },
    { name: "Table", icon: Table },
    { name: "Tablet 01", icon: Tablet01 },
    { name: "Tablet 02", icon: Tablet02 },
    { name: "Tag 01", icon: Tag01 },
    { name: "Tag 02", icon: Tag02 },
    { name: "Tag 03", icon: Tag03 },
    { name: "Target 01", icon: Target01 },
    { name: "Target 02", icon: Target02 },
    { name: "Target 03", icon: Target03 },
    { name: "Target 04", icon: Target04 },
    { name: "Target 05", icon: Target05 },
    { name: "Telescope", icon: Telescope },
    { name: "Terminal", icon: Terminal },
    { name: "Terminal Browser", icon: TerminalBrowser },
    { name: "Terminal Circle", icon: TerminalCircle },
    { name: "Terminal Square", icon: TerminalSquare },
    { name: "Text Input", icon: TextInput },
    { name: "Thermometer 01", icon: Thermometer01 },
    { name: "Thermometer 02", icon: Thermometer02 },
    { name: "Thermometer 03", icon: Thermometer03 },
    { name: "Thermometer Cold", icon: ThermometerCold },
    { name: "Thermometer Warm", icon: ThermometerWarm },
    { name: "Thumbs Down", icon: ThumbsDown },
    { name: "Thumbs Up", icon: ThumbsUp },
    { name: "Ticket 01", icon: Ticket01 },
    { name: "Ticket 02", icon: Ticket02 },
    { name: "Toggle 01 Left", icon: Toggle01Left },
    { name: "Toggle 01 Right", icon: Toggle01Right },
    { name: "Toggle 02 Left", icon: Toggle02Left },
    { name: "Toggle 02 Right", icon: Toggle02Right },
    { name: "Toggle 03 Left", icon: Toggle03Left },
    { name: "Toggle 03 Right", icon: Toggle03Right },
    { name: "Tool 01", icon: Tool01 },
    { name: "Tool 02", icon: Tool02 },
    { name: "Train", icon: Train },
    { name: "Tram", icon: Tram },
    { name: "Transform", icon: Transform },
    { name: "Translate 01", icon: Translate01 },
    { name: "Translate 02", icon: Translate02 },
    { name: "Trash 01", icon: Trash01 },
    { name: "Trash 02", icon: Trash02 },
    { name: "Trash 03", icon: Trash03 },
    { name: "Trash 04", icon: Trash04 },
    { name: "Trend Down 01", icon: TrendDown01 },
    { name: "Trend Down 02", icon: TrendDown02 },
    { name: "Trend Up 01", icon: TrendUp01 },
    { name: "Trend Up 02", icon: TrendUp02 },
    { name: "Triangle", icon: Triangle },
    { name: "Trophy 01", icon: Trophy01 },
    { name: "Trophy 02", icon: Trophy02 },
    { name: "Truck 01", icon: Truck01 },
    { name: "Truck 02", icon: Truck02 },
    { name: "Tv 01", icon: Tv01 },
    { name: "Tv 02", icon: Tv02 },
    { name: "Tv 03", icon: Tv03 },
    { name: "Type 01", icon: Type01 },
    { name: "Type 02", icon: Type02 },
    { name: "Type Square", icon: TypeSquare },
    { name: "Type Strikethrough 01", icon: TypeStrikethrough01 },
    { name: "Type Strikethrough 02", icon: TypeStrikethrough02 },
    { name: "Umbrella 01", icon: Umbrella01 },
    { name: "Umbrella 02", icon: Umbrella02 },
    { name: "Umbrella 03", icon: Umbrella03 },
    { name: "Underline 01", icon: Underline01 },
    { name: "Underline 02", icon: Underline02 },
    { name: "Underline Square", icon: UnderlineSquare },
    { name: "Upload 01", icon: Upload01 },
    { name: "Upload 02", icon: Upload02 },
    { name: "Upload 03", icon: Upload03 },
    { name: "Upload 04", icon: Upload04 },
    { name: "Upload Cloud 01", icon: UploadCloud01 },
    { name: "Upload Cloud 02", icon: UploadCloud02 },
    { name: "Usb Flash Drive", icon: UsbFlashDrive },
    { name: "User 01", icon: User01 },
    { name: "User 02", icon: User02 },
    { name: "User 03", icon: User03 },
    { name: "User Check 01", icon: UserCheck01 },
    { name: "User Check 02", icon: UserCheck02 },
    { name: "User Circle", icon: UserCircle },
    { name: "User Down 01", icon: UserDown01 },
    { name: "User Down 02", icon: UserDown02 },
    { name: "User Edit", icon: UserEdit },
    { name: "User Left 01", icon: UserLeft01 },
    { name: "User Left 02", icon: UserLeft02 },
    { name: "User Minus 01", icon: UserMinus01 },
    { name: "User Minus 02", icon: UserMinus02 },
    { name: "User Plus 01", icon: UserPlus01 },
    { name: "User Plus 02", icon: UserPlus02 },
    { name: "User Right 01", icon: UserRight01 },
    { name: "User Right 02", icon: UserRight02 },
    { name: "Users 01", icon: Users01 },
    { name: "Users 02", icon: Users02 },
    { name: "Users 03", icon: Users03 },
    { name: "Users Check", icon: UsersCheck },
    { name: "Users Down", icon: UsersDown },
    { name: "Users Edit", icon: UsersEdit },
    { name: "Users Left", icon: UsersLeft },
    { name: "Users Minus", icon: UsersMinus },
    { name: "Users Plus", icon: UsersPlus },
    { name: "User Square", icon: UserSquare },
    { name: "Users Right", icon: UsersRight },
    { name: "Users Up", icon: UsersUp },
    { name: "Users X", icon: UsersX },
    { name: "User Up 01", icon: UserUp01 },
    { name: "User Up 02", icon: UserUp02 },
    { name: "User X 01", icon: UserX01 },
    { name: "User X 02", icon: UserX02 },
    { name: "Variable", icon: Variable },
    { name: "Video Recorder", icon: VideoRecorder },
    { name: "Video Recorder Off", icon: VideoRecorderOff },
    { name: "Virus", icon: Virus },
    { name: "Voicemail", icon: Voicemail },
    { name: "Volume Max", icon: VolumeMax },
    { name: "Volume Min", icon: VolumeMin },
    { name: "Volume Minus", icon: VolumeMinus },
    { name: "Volume Plus", icon: VolumePlus },
    { name: "Volume X", icon: VolumeX },
    { name: "Wallet 01", icon: Wallet01 },
    { name: "Wallet 02", icon: Wallet02 },
    { name: "Wallet 03", icon: Wallet03 },
    { name: "Wallet 04", icon: Wallet04 },
    { name: "Wallet 05", icon: Wallet05 },
    { name: "Watch Circle", icon: WatchCircle },
    { name: "Watch Square", icon: WatchSquare },
    { name: "Waves", icon: Waves },
    { name: "Webcam 01", icon: Webcam01 },
    { name: "Webcam 02", icon: Webcam02 },
    { name: "Wifi", icon: Wifi },
    { name: "Wifi Off", icon: WifiOff },
    { name: "Wind 01", icon: Wind01 },
    { name: "Wind 02", icon: Wind02 },
    { name: "Wind 03", icon: Wind03 },
    { name: "X", icon: X },
    { name: "X Circle", icon: XCircle },
    { name: "X Close", icon: XClose },
    { name: "X Square", icon: XSquare },
    { name: "Youtube", icon: Youtube },
    { name: "Zap", icon: Zap },
    { name: "Zap Circle", icon: ZapCircle },
    { name: "Zap Fast", icon: ZapFast },
    { name: "Zap Off", icon: ZapOff },
    { name: "Zap Square", icon: ZapSquare },
    { name: "Zoom In", icon: ZoomIn },
    { name: "Zoom Out", icon: ZoomOut },
];

export default {
    title: "Foundations/Icons",
    decorators: [
        (Story: FC) => (
            <div className="flex min-h-screen w-full overflow-auto bg-primary p-8">
                <Story />
            </div>
        ),
    ],
};

export const Icons = () => (
    <div className="flex flex-wrap gap-6">
        {icons.map(({ name, icon: Icon }) => (
            <div key={name} className="flex w-24 flex-col items-center gap-2">
                <Icon className="size-5 text-fg-quaternary" />
                <span className="text-center text-xs text-tertiary">{name}</span>
            </div>
        ))}
    </div>
);
