/**
 * Content scaffolding CLI. Stubs out a component doc page pre-filled
 * with the site's standard heading skeleton (see content/docs -- every
 * page follows Overview -> Installation -> Usage -> Props -> Examples ->
 * Accessibility -> Related), auto-populating Props (from
 * .generated/props.json) and Examples (from .generated/demo-exports.json)
 * from what's already been generated by `pnpm run docs:sync`.
 *
 * Usage:
 *   tsx apps/docs/scripts/new-doc.ts <category> <group>
 *   tsx apps/docs/scripts/new-doc.ts --all <category>
 *
 * <category> is a packages/ui/components/ folder name: base | application | foundations | shared-assets
 * <group> is a subfolder name (e.g. "buttons") or, for loose top-level
 * files (e.g. components/foundations/dot-icon.tsx), the file's basename
 * without extension (e.g. "dot-icon").
 *
 * Run `pnpm run docs:sync` first so the generated data this script
 * reads from is current.
 */
import fs from "node:fs";
import path from "node:path";

const SCRIPT_DIR = import.meta.dirname;
const DOCS_ROOT = path.join(SCRIPT_DIR, "..");
const REPO_ROOT = path.join(DOCS_ROOT, "..", "..");
const UI_ROOT = path.join(REPO_ROOT, "packages", "ui");
const COMPONENTS_ROOT = path.join(UI_ROOT, "components");
const GENERATED_DIR = path.join(DOCS_ROOT, ".generated");
const CONTENT_ROOT = path.join(DOCS_ROOT, "content", "docs");

const ICON_HEAVY_GROUPS = new Set(["icons", "payment-icons", "integration-icons", "social-icons"]);

const CATEGORIES: Record<string, { dir: string; title: string }> = {
    base: { dir: "base-components", title: "Base Components" },
    application: { dir: "application", title: "Application" },
    foundations: { dir: "foundations", title: "Foundations" },
    "shared-assets": { dir: "shared-assets", title: "Shared Assets" },
};

const KNOWN_ACRONYMS: Record<string, string> = { ai: "AI", qr: "QR", otp: "OTP" };

function titleCase(slug: string): string {
    return slug
        .split("-")
        .map((word) => KNOWN_ACRONYMS[word.toLowerCase()] ?? word[0].toUpperCase() + word.slice(1))
        .join(" ");
}

/** "PrimaryDestructiveDemo" -> "Primary Destructive" */
function titleCaseFromExportName(exportName: string): string {
    const stripped = exportName.replace(/Demo$/, "");
    const spaced = stripped.replace(/([a-z0-9])([A-Z])/g, "$1 $2").replace(/([A-Z]+)([A-Z][a-z])/g, "$1 $2");
    return spaced.trim() || exportName;
}

function readJson<T>(file: string, fallback: T): T {
    if (!fs.existsSync(file)) return fallback;
    return JSON.parse(fs.readFileSync(file, "utf8"));
}

function ensureMeta(dir: string, title: string, entry?: string) {
    fs.mkdirSync(dir, { recursive: true });
    const metaPath = path.join(dir, "meta.json");
    const meta: { title: string; pages: string[] } = fs.existsSync(metaPath) ? JSON.parse(fs.readFileSync(metaPath, "utf8")) : { title, pages: [] };
    if (entry && !meta.pages.includes(entry)) meta.pages.push(entry);
    fs.writeFileSync(metaPath, `${JSON.stringify(meta, null, 4)}\n`);
}

interface DemoPair {
    id: string;
    exportName: string;
}

/**
 * Picks the single best example to lead the Overview section with:
 * prefer the demo file whose id exactly matches the group name (the
 * "main" component per CONTRIBUTING.md's convention), and within it an
 * export literally named Primary/Default/Basic if one exists -- falling
 * back to the first example found at all otherwise. Groups containing
 * several unrelated demo files (e.g. "buttons/" has buttons.demo.tsx,
 * app-store-buttons.demo.tsx, social-buttons.demo.tsx) would otherwise
 * lead with whichever file sorts first alphabetically, which is rarely
 * the component a visitor actually means by the group's name.
 */
function pickHero(pairs: DemoPair[], category: string, group: string): DemoPair | undefined {
    if (pairs.length === 0) return undefined;
    const primaryId = `${category}/${group}/${group}`;
    const pool = pairs.some((p) => p.id === primaryId) ? pairs.filter((p) => p.id === primaryId) : pairs;
    const named = pool.find((p) => /^(primary|default|basic)$/i.test(p.exportName.replace(/Demo$/, "")));
    return named ?? pool[0];
}

/**
 * One `import { DisplayName } from "@/components/category/group/file"`
 * line per distinct component file successfully docgen'd for this
 * group (see writeProps in sync-content.ts) -- reads real export/path
 * pairs instead of guessing a single export name from the group's slug,
 * which breaks for any group backing more than one real component.
 */
function installLines(category: string, group: string, propsIds: string[], propsData: Record<string, unknown[]>): string[] {
    if (propsIds.length === 0) {
        return [
            "```ts",
            `import { ${titleCase(group).replace(/\s+/g, "")} } from "@/components/${category}/${group}";`,
            "```",
            "",
            "{/* TODO: props couldn't be auto-extracted -- confirm the real named export(s) above by hand. */}",
        ];
    }
    const importLines = propsIds.map((id) => {
        const displayName = (propsData[id]?.[0] as { displayName?: string } | undefined)?.displayName ?? id.split("/").pop();
        return `import { ${displayName} } from "@/components/${id}";`;
    });
    return ["```ts", ...importLines, "```"];
}

function siblingGroups(category: string, group: string): string[] {
    const categoryDir = path.join(COMPONENTS_ROOT, category);
    if (!fs.existsSync(categoryDir)) return [];
    return fs
        .readdirSync(categoryDir, { withFileTypes: true })
        .filter((e) => e.isDirectory() && e.name !== group && !ICON_HEAVY_GROUPS.has(e.name))
        .map((e) => e.name)
        .slice(0, 3);
}

function generateDoc(category: string, group: string) {
    const categoryInfo = CATEGORIES[category];
    if (!categoryInfo) {
        throw new Error(`Unknown category "${category}". Expected one of: ${Object.keys(CATEGORIES).join(", ")}`);
    }

    const demoExports = readJson<Record<string, string[]>>(path.join(GENERATED_DIR, "demo-exports.json"), {});
    const propsData = readJson<Record<string, unknown[]>>(path.join(GENERATED_DIR, "props.json"), {});

    const demoIds = Object.keys(demoExports)
        .filter((id) => id === `${category}/${group}` || id.startsWith(`${category}/${group}/`))
        .sort();
    const propsIds = Object.keys(propsData)
        .filter((id) => id === `${category}/${group}` || id.startsWith(`${category}/${group}/`))
        .sort();

    const pairs = demoIds.flatMap((id) => demoExports[id].map((exportName) => ({ id, exportName })));

    const contentDir = path.join(CONTENT_ROOT, categoryInfo.dir);
    const slug = group;
    const title = titleCase(group);

    const lines: string[] = [];
    lines.push("---");
    lines.push(`title: ${title}`);
    lines.push(`description: TODO -- one sentence describing ${title}'s primary use case.`);
    lines.push("---", "");

    const hero = pickHero(pairs, category, group);

    lines.push("## Overview", "");
    if (hero) {
        lines.push(`<ComponentPreview demo="${hero.id}" export="${hero.exportName}" />`, "");
    } else {
        lines.push(
            "{/* TODO: no *.demo.tsx / *.story.tsx found for this group yet -- add one under components/, run `pnpm run docs:sync`, then re-run this script. */}",
            "",
        );
    }

    lines.push("## Installation", "");
    lines.push(...installLines(category, group, propsIds, propsData), "");

    lines.push("## Usage", "");
    lines.push("{/* TODO: minimal usage snippet. */}", "");

    lines.push("## Props", "");
    if (propsIds.length > 0) {
        for (const id of propsIds) {
            const displayName = (propsData[id]?.[0] as { displayName?: string } | undefined)?.displayName ?? id.split("/").pop();
            lines.push(`**${displayName}**`, "");
            lines.push(`<PropsTable component="${id}" />`, "");
        }
    } else {
        lines.push("{/* TODO: props couldn't be auto-extracted for this group. Write a plain markdown table by hand. */}", "");
    }

    lines.push("## Examples", "");
    if (pairs.length > 0) {
        let previousId: string | undefined;
        for (const { id, exportName } of pairs) {
            // When a group backs several unrelated demo files (e.g.
            // "buttons/" has buttons.demo.tsx, app-store-buttons.demo.tsx,
            // social-buttons.demo.tsx), label each file's cluster of
            // examples so the section reads as organized groups rather
            // than one flat wall -- a bold label, not a heading, so it
            // doesn't add a 3rd level to every page's Table of Contents.
            if (id !== previousId && demoIds.length > 1) {
                const fileLabel = id === `${category}/${group}` ? title : titleCase(id.split("/").pop() ?? id);
                lines.push(`**${fileLabel}**`, "");
                previousId = id;
            }
            lines.push(`### ${titleCaseFromExportName(exportName)}`, "");
            lines.push(`<ComponentPreview demo="${id}" export="${exportName}" />`, "");
        }
    } else {
        lines.push("{/* TODO: add examples once a *.demo.tsx exists for this group. */}", "");
    }

    lines.push("## Accessibility", "");
    lines.push("{/* TODO: keyboard interactions and ARIA notes. */}", "");

    lines.push("## Related", "");
    const related = siblingGroups(category, group);
    if (related.length > 0) {
        for (const sibling of related) {
            lines.push(`- [${titleCase(sibling)}](/docs/${categoryInfo.dir}/${sibling})`);
        }
        lines.push("");
    } else {
        lines.push("{/* TODO: link 2-4 related components. */}", "");
    }

    fs.mkdirSync(contentDir, { recursive: true });
    fs.writeFileSync(path.join(contentDir, `${slug}.mdx`), `${lines.join("\n").trimEnd()}\n`);
    ensureMeta(contentDir, categoryInfo.title, slug);
    ensureMeta(CONTENT_ROOT, "Documentation", categoryInfo.dir);

    console.log(`[new-doc] wrote content/docs/${categoryInfo.dir}/${slug}.mdx (${pairs.length} examples, ${propsIds.length} props tables)`);
}

function allGroupsFor(category: string): string[] {
    const categoryDir = path.join(COMPONENTS_ROOT, category);
    const folders = fs
        .readdirSync(categoryDir, { withFileTypes: true })
        .filter((e) => e.isDirectory() && !ICON_HEAVY_GROUPS.has(e.name))
        .map((e) => e.name);
    const looseFiles = fs
        .readdirSync(categoryDir, { withFileTypes: true })
        .filter((e) => e.isFile() && e.name.endsWith(".tsx") && !e.name.endsWith(".demo.tsx") && !e.name.endsWith(".story.tsx"))
        .map((e) => e.name.replace(/\.tsx$/, ""));
    return [...folders, ...looseFiles].sort();
}

function main() {
    const args = process.argv.slice(2);

    if (args[0] === "--all") {
        const category = args[1];
        if (!category) throw new Error("Usage: new-doc.ts --all <category>");
        for (const group of allGroupsFor(category)) {
            generateDoc(category, group);
        }
        return;
    }

    const [category, group] = args;
    if (!category || !group) {
        throw new Error("Usage: new-doc.ts <category> <group>   (or: new-doc.ts --all <category>)");
    }
    generateDoc(category, group);
}

main();
